// ============================================================
// FILE: LanguageContext.tsx
// SECTION: shared > contexts
// PURPOSE: App-wide language state manage karna â€” English aur Urdu.
//          Puri app ka translations data yahan stored hai.
//          useLanguage() hook se koi bhi component translations access kar sakta hai.
// ============================================================
import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ur' | 'ar' | 'hi' | 'es' | 'fr' | 'zh' | 'tr';

export const languageLabels: Record<Language, { name: string; flag: string; nativeName: string }> = {
  en: { name: 'English', flag: '🇬🇧', nativeName: 'English' },
  ur: { name: 'Urdu', flag: '🇵🇰', nativeName: 'اردو' },
  ar: { name: 'Arabic', flag: '🇸🇦', nativeName: 'العربية' },
  hi: { name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी' },
  es: { name: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
  fr: { name: 'French', flag: '🇫🇷', nativeName: 'Français' },
  zh: { name: 'Chinese', flag: '🇨🇳', nativeName: '中文' },
  tr: { name: 'Turkish', flag: '🇹🇷', nativeName: 'Türkçe' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.features': 'Features',
    'nav.howItWorks': 'How It Works',
    'nav.foodie': 'For Foodies',
    'nav.partner': 'For Partners',
    'nav.signIn': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.policies': 'Policies',
    'dash.overview': 'Overview',
    'dash.liveOrders': 'Live Orders',
    'dash.menuManager': 'Menu Manager',
    'dash.aiAssistant': 'AI Assistant',
    'dash.qrBuilder': 'QR Builder',
    'dash.settings': 'Settings',
    'dash.signOut': 'Sign Out',
    'dash.adminPortal': 'Admin Portal',
    'dash.morning': 'Good Morning',
    'dash.afternoon': 'Good Afternoon',
    'dash.evening': 'Good Evening',
    'settings.title': 'Live Magic Canvas',
    'settings.subtitle': 'Design your brand and configure system operations in real-time.',
    'settings.saveChanges': 'Save Changes',
    'settings.profile': 'Restaurant Profile',
    'settings.localization': 'Portal Language',
    'settings.security': 'Security & Access',
    'hero.badge': 'AI-Powered Voice Technology',
    'hero.badgeText': 'AI-POWERED VOICE ORDERING',
    'hero.headlineMain1': 'Order Smarter.',
    'hero.headlineMain2': 'Say It. Savor It.',
    'hero.watchDemo': 'Watch Demo',
    'hero.liveOrdering': 'Live Ordering',
    'hero.voicePowered': 'Voice Powered',
    'hero.instantQR': 'Instant QR',
    'hero.scroll': 'Scroll',
    'hero.demoVoicePill': '"Order two Zinger Burgers..."',
    'hero.headline1': 'Revolutionizing Taste',
    'hero.headline2': 'with Voice AI',
    'hero.subheadline': 'Experience the future of food discovery where your voice unlocks personalized culinary journeys.',
    'hero.tryVoice': 'Try Voice Search',
    'about.subtitle': 'About SaySavor',
    'about.title': 'Transforming How You Experience Food',
    'about.title1': 'Transforming How You',
    'about.title2': 'Experience Food',
    'about.description': 'SaySavor combines cutting-edge voice AI technology with a passion for great food. We help you discover restaurants, cuisines, and dishes tailored to your unique taste preferences.',
    'about.learnMore': 'Learn More',
    'about.globalReach': 'Global Reach',
    'about.globalReachDesc': 'Discover restaurants and cuisines from around the world, all with a simple voice command.',
    'about.secure': 'Secure & Private',
    'about.secureDesc': 'Your data and preferences are protected with enterprise-grade security.',
    'about.fast': 'Lightning Fast',
    'about.fastDesc': 'Get instant recommendations powered by our advanced AI engine.',
    'features.badge': 'Powerful Features',
    'features.title': 'Voice-Powered Food Ordering',
    'features.title1': 'Built for',
    'features.title2': 'Everyone',
    'features.subtitle': 'Experience food ordering that understands you—your culture, your needs, your preferences.',
    'features.cultural': 'Cultural Contextualization',
    'features.culturalDesc': 'Intelligent filtering based on dietary preferences and religious requirements. Respecting every culture, one meal at a time.',
    'features.accessibility': 'Universal Accessibility',
    'features.accessibilityDesc': 'Designed for everyone with WCAG 2.1 Level AA compliance. High-contrast modes and full screen reader support included.',
    'features.ai': 'Emotionally Intelligent AI',
    'features.aiDesc': 'Our AI learns your preferences, dietary restrictions, and cultural contexts to provide truly personalized recommendations.',
    'features.qr': 'Instant QR Ordering',
    'features.qrDesc': 'Scan a QR code and place your order in seconds. No app download required—just point, scan, and savor.',
    'features.multilang': 'Multilingual Support',
    'features.multilangDesc': 'Support for 50+ languages so every customer feels at home, no matter where they are from.',
    'features.analytics': 'Smart Analytics',
    'features.analyticsDesc': 'Restaurant owners get real-time insights into popular dishes, peak hours, and customer behavior.',
    'how.subtitle': 'Simple Process',
    'how.title': 'How It Works',
    'how.step1Title': 'Scan & Browse',
    'how.step1Desc': 'Scan the QR code on your table to instantly access the full digital menu — no app needed.',
    'how.step2Title': 'Order by Voice',
    'how.step2Desc': 'Speak your order naturally in your language. Our AI understands your dialect and preferences.',
    'how.step3Title': 'Savor Your Meal',
    'how.step3Desc': 'Sit back and relax while your order is prepared. Real-time updates keep you informed every step of the way.',
    'howItWorks.title': 'How It Works',
    'howItWorks.subtitle': 'Three simple steps to your perfect meal',
    'howItWorks.step1Title': 'Speak Your Craving',
    'howItWorks.step1Desc': 'Simply tell us what you want in your language. Our AI understands natural speech in 50+ languages.',
    'howItWorks.step2Title': 'AI Finds Your Match',
    'howItWorks.step2Desc': 'Our intelligent engine analyzes your preferences, location, and dietary needs to find perfect matches.',
    'howItWorks.step3Title': 'Enjoy Your Meal',
    'howItWorks.step3Desc': 'Order with one tap and track your food in real-time. Delicious food, delivered your way.',
    'howItWorks.learnMore': 'Learn more about our process',
    'testimonials.title': 'What People Say',
    'testimonials.subtitle': 'Join thousands of satisfied users who have transformed their food ordering experience.',
    'testimonials.t1Name': 'Ahmad Karimi',
    'testimonials.t1Role': 'Food Enthusiast, Tehran',
    'testimonials.t1Text': 'SaySavor changed how I order food. I just speak naturally and it understands me perfectly—even my local dialect!',
    'testimonials.t2Name': 'Samira Benali',
    'testimonials.t2Role': 'Restaurant Owner, Casablanca',
    'testimonials.t2Text': 'Since integrating SaySavor, our orders increased by 40%. The analytics dashboard is incredibly insightful.',
    'testimonials.t3Name': 'Ravi Mehta',
    'testimonials.t3Role': 'Foodie & Traveler, Mumbai',
    'testimonials.t3Text': 'Finally, an app that respects my dietary restrictions without me repeating myself. The AI just gets it.',
    'cta.badge': 'Join 500K+ Users',
    'cta.title': 'Ready to Transform Your Food Experience?',
    'cta.subtitle': 'Download SaySavor today and discover a world of culinary possibilities at your voice command.',
    'cta.description': 'Join over 500,000 food lovers who already use SaySavor to order smarter, faster, and in their own language.',
    'cta.getStarted': 'Get Started Free',
    'cta.scheduleDemo': 'Schedule a Demo',
    'cta.downloadNow': 'Download Now',
    'cta.becomePartner': 'Become a Partner',
    'persona.title': 'Choose Your Journey',
    'persona.title1': 'Choose Your',
    'persona.title2': 'Journey',
    'persona.subtitle': "Whether you're here to discover amazing food or grow your restaurant business, we've got you covered.",
    'persona.foodie': 'I am a Foodie',
    'persona.foodieSubtitle': 'Discover culinary experiences tailored just for you',
    'persona.foodieDesc': 'Explore hundreds of restaurants, order in your language, and enjoy food tailored to your dietary preferences.',
    'persona.foodieCta': 'Explore as a Foodie',
    'persona.partner': 'I am a Partner',
    'persona.partnerSubtitle': 'Grow your restaurant with intelligent analytics',
    'persona.partnerDesc': 'Boost your revenue with AI-driven insights, voice ordering, and seamless customer management.',
    'persona.partnerCta': 'Join as a Partner',
    'persona.getStarted': 'Get Started',
    'persona.exploreNow': 'Explore Now',
    'persona.restaurantsCount': '1,200+ Restaurants',
    'persona.foodieFeature1': 'Voice-powered ordering in your language',
    'persona.foodieFeature2': 'AI-curated restaurant recommendations',
    'persona.foodieFeature3': 'Cultural & dietary preference filtering',
    'persona.foodieFeature4': 'Real-time order tracking',
    'persona.partnerFeature1': 'Advanced analytics dashboard',
    'persona.partnerFeature2': 'AI-powered demand forecasting',
    'persona.partnerFeature3': 'Multi-channel order management',
    'persona.partnerFeature4': 'Customer insights & trends',
    'policies.subtitle': 'Our Commitment to You',
    'footer.description': 'Revolutionizing food ordering with voice AI technology that understands your culture and preferences.',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.resources': 'Resources',
    'footer.legal': 'Legal',
    'footer.copyright': '© 2025 SaySavor. All rights reserved.',
    'footer.madeWith': 'Made with',
    'footer.forFoodLovers': 'for food lovers worldwide',
    'policies.title': 'Legal & Policies',
    'policies.privacy': 'Privacy Policy',
    'policies.terms': 'Terms of Service',
    'policies.cookies': 'Cookie Policy',
    'policies.partner': 'Partner Guidelines',
    'policies.heroDescription': 'Transparency is important to us. Here you\'ll find all our legal documents and policies.',
    'policies.lastUpdated': 'Last updated',
    'policies.december2025': 'December 2025',
    'policies.contactTitle': 'Questions About Our Policies?',
    'policies.contactDescription': 'If you have any questions about our policies, please don\'t hesitate to contact us.',
    'policies.contactButton': 'Contact Legal Team',
    'policies.privacyDesc': 'How we collect, use, and protect your personal data.',
    'policies.infoCollect': 'Information We Collect',
    'policies.infoCollectContent': 'We collect information you provide directly, such as account details, order history, and voice recordings when using voice features.',
    'policies.howWeUse': 'How We Use Your Information',
    'policies.howWeUseContent': 'Your data is used to process orders, personalize recommendations, improve our AI models, and communicate with you.',
    'policies.dataSharing': 'Data Sharing',
    'policies.dataSharingContent': 'We share necessary information with restaurant partners to fulfill orders. We never sell your personal data.',
    'policies.yourRights': 'Your Rights',
    'policies.yourRightsContent': 'You have the right to access, correct, or delete your data. Contact us at privacy@saysavor.com.',
    'policies.termsDesc': 'Terms and conditions for using SaySavor.',
    'policies.accountResp': 'Account Responsibilities',
    'policies.accountRespContent': 'You are responsible for maintaining the security of your account and for all activities under your account.',
    'policies.serviceUsage': 'Service Usage',
    'policies.serviceUsageContent': 'SaySavor is provided for personal, non-commercial food ordering. Misuse may result in account suspension.',
    'policies.orderPolicies': 'Order Policies',
    'policies.orderPoliciesContent': 'Orders are binding once confirmed. Cancellation policies are set by individual restaurant partners.',
    'policies.liability': 'Limitation of Liability',
    'policies.liabilityContent': 'SaySavor is not liable for food quality issues, which are the responsibility of restaurant partners.',
    'policies.cookiesDesc': 'How we use cookies and tracking technologies.',
    'policies.essentialCookies': 'Essential Cookies',
    'policies.essentialCookiesContent': 'Required for basic functionality like login sessions and cart management. Cannot be disabled.',
    'policies.analyticsCookies': 'Analytics Cookies',
    'policies.analyticsCookiesContent': 'Help us understand how users interact with our platform to improve the experience.',
    'policies.prefCookies': 'Preference Cookies',
    'policies.prefCookiesContent': 'Remember your settings like language preferences and favorite restaurants.',
    'policies.managingCookies': 'Managing Cookies',
    'policies.managingCookiesContent': 'You can manage cookie preferences in your browser settings or through our cookie consent banner.',
    'policies.partnerDesc': 'Guidelines for restaurant partners.',
    'policies.qualityStandards': 'Quality Standards',
    'policies.qualityStandardsContent': 'Partners must maintain food safety standards and accurate menu information.',
    'policies.commission': 'Commission Structure',
    'policies.commissionContent': 'Standard commission is 15-25% per order depending on partnership tier.',
    'policies.orderFulfillment': 'Order Fulfillment',
    'policies.orderFulfillmentContent': 'Orders must be accepted within 5 minutes. Preparation times should be accurate.',
    'policies.supportResources': 'Support Resources',
    'policies.supportResourcesContent': 'Partners have access to our Partner Portal, dedicated support team, and analytics dashboard.',
    'policies.privacyB1': 'Data collection practices',
    'policies.privacyB2': 'Third-party sharing',
    'policies.privacyB3': 'Your rights',
    'policies.termsB1': 'User responsibilities',
    'policies.termsB2': 'Service limitations',
    'policies.termsB3': 'Account policies',
    'policies.cookiesB1': 'Cookie types',
    'policies.cookiesB2': 'Managing preferences',
    'policies.cookiesB3': 'Analytics usage',
    'policies.partnerB1': 'Quality standards',
    'policies.partnerB2': 'Commission structure',
    'policies.partnerB3': 'Support resources',
    'policies.transparencyPriority': 'Transparency is our priority',
    'policies.readMore': 'Read more',
    'about.mission': 'Our Mission',
    'about.missionDesc': 'To democratize food discovery by breaking language barriers and making every cuisine accessible to everyone, everywhere.',
    'about.vision': 'Our Vision',
    'about.visionDesc': 'A world where your voice is the only thing you need to explore, discover, and enjoy the perfect meal.',
    'about.innovation': 'Our Innovation',
    'about.innovationDesc': 'Leveraging cutting-edge AI and voice recognition to create seamless, culturally-aware food experiences.',
    'about.storyP1': 'SaySavor was born from a simple frustration: ordering food in a foreign language shouldn\'t be hard. Our founder experienced this firsthand while traveling across Asia, struggling to communicate dietary preferences and discover local cuisines.',
    'about.storyP2': 'In 2025, we assembled a team of AI researchers, food enthusiasts, and accessibility advocates to build something revolutionary—a platform where anyone could order food in their native language.',
    'about.storyP3': 'Today, SaySavor serves over 500,000 users across 50+ countries, processing orders in 20+ languages with 90% voice recognition accuracy. But we\'re just getting started.',
    'about.meetTeam': 'Meet Our',
    'about.team': 'Team',
    'about.readyToJoin': 'Ready to Join the Revolution?',
    'about.ctaDesc': 'Whether you\'re a food lover or a restaurant partner, there\'s a place for you at SaySavor.',
    'about.startFoodie': 'Start as Foodie',
    'about.heroTitle1': 'Transforming How The World',
    'about.heroTitle2': 'Discovers Food',
    'about.heroDesc': 'We believe that great food should be accessible to everyone, regardless of language or location. SaySavor is on a mission to connect people with their perfect meal using the power of voice AI.',
    'about.storyTitle': 'Our Story',
    'about.statsUsers': 'Active Users',
    'about.statsCountries': 'Countries',
    'about.statsLangs': 'Languages',
    'features.voice': 'Smart Voice Search',
    'features.voiceDesc': 'Speak naturally in any language. Our AI understands context, dialects, accents, and food-specific terminology.',
    'features.realtime': 'Real-Time Updates',
    'features.realtimeDesc': 'Track your order from kitchen to doorstep with live updates, accurate ETAs, and instant notifications.',
    'features.notifications': 'Smart Notifications',
    'features.notifDesc': 'Personalized deals and order updates',
    'features.everythingYou': 'Everything You',
    'features.need': 'Need',
    'features.and': 'And',
    'features.muchMore': 'Much More',
    'features.expDiff': 'Experience the Difference',
    'features.joinHundreds': 'Join hundreds of thousands of users who have transformed their food ordering experience.',
    'howItWorks.startOrdering': 'Start Ordering Now',
    'howItWorks.tryYourself': 'Ready to Try It Yourself?',
    'howItWorks.tryDesc': 'Experience the magic of voice-powered food discovery. It\'s free to get started.',
    'howItWorks.watchDemo': 'Watch Demo Video',
    'howItWorks.step1Detail1': 'Natural language processing understands context',
    'howItWorks.step1Detail2': 'Support for 20+ languages and dialects',
    'howItWorks.step1Detail3': 'Accent and pronunciation tolerance',
    'howItWorks.step1Detail4': 'Works even in noisy environments',
    'howItWorks.step2Detail1': 'Personalized based on your taste profile',
    'howItWorks.step2Detail2': 'Filters for dietary and cultural preferences',
    'howItWorks.step2Detail3': 'Real-time availability and wait times',
    'howItWorks.step2Detail4': 'Price range and distance optimization',
    'howItWorks.step3Detail1': 'One-tap or voice-activated checkout',
    'howItWorks.step3Detail2': 'Real-time order tracking with GPS',
    'howItWorks.step3Detail3': 'Direct communication with restaurant',
    'howItWorks.step3Detail4': 'Rate and save favorites for next time',
    'features.benefit1v': '20+ languages supported',
    'features.benefit2v': 'Dialect recognition',
    'features.benefit3v': '90% accuracy rate',
    'features.benefit4v': 'Offline mode available',
    'features.benefit1a': 'Taste profile learning',
    'features.benefit2a': 'Mood-based suggestions',
    'features.benefit3a': 'Time-aware recommendations',
    'features.benefit4a': 'Favorite auto-detection',
    'features.benefit1r': 'Live GPS tracking',
    'features.benefit2r': 'Kitchen status updates',
    'features.benefit3r': 'Driver communication',
    'features.benefit4r': 'Accurate ETA predictions',
    'foodie.t1Name': 'Ahmed K.',
    'foodie.t1Location': 'Lahore',
    'foodie.t1Text': 'Finally an app that understands Urdu! Game changer.',
    'foodie.t2Name': 'Sarah M.',
    'foodie.t2Location': 'Dubai',
    'foodie.t2Text': 'The halal filter is so accurate. Love it!',
    'foodie.t3Name': 'John D.',
    'foodie.t3Location': 'NYC',
    'foodie.t3Text': 'Voice ordering while driving is amazing.',
    'scroll.step1Title': 'Digital Gastronomy',
    'scroll.step1Heading': 'A Cinematic Presentation',
    'scroll.step1Desc': 'Scroll to experience the 3D rendering of our dishes. See every delicious detail.',
    'scroll.step2Title': 'AI Precision',
    'scroll.step2Heading': 'Perfectly Crafted Code',
    'scroll.step2Desc': 'Just like our ingredients, our AI algorithms are hand-picked for the best recommendation results.',
    'scroll.step3Title': 'Voice Interface',
    'scroll.step3Heading': 'Speak Your Craving',
    'scroll.step3Desc': 'Zero typing required. Natural Language Processing understands context, dialects, and cuisine jargon.',
    'scroll.step4Heading': 'Say It. Savor It.',
    'scroll.step4Desc': 'Continue scrolling to explore our platform.',
    'foodie.saveFav': 'Save Favorites',
    'foodie.saveFavDesc': 'Quick access to loved restaurants',
    'foodie.easyReorder': 'Easy Reorder',
    'foodie.easyReorderDesc': 'One-tap to repeat orders',
    'foodie.voiceDemo': 'Voice Demo Preview',
    'foodie.lovedBy': 'Loved by',
    'foodie.foodies': 'Foodies',
    'foodie.readyOrder': 'Ready to Order?',
    'foodie.join500k': 'Join 500K+ food lovers who order with their voice intuitively.',
    'foodie.getFree': 'Get Started Free',
  },
  ur: {
    'nav.home': 'ہوم',
    'nav.about': 'ہمارے بارے میں',
    'nav.features': 'خصوصیات',
    'nav.howItWorks': 'یہ کیسے کام کرتا ہے',
    'nav.foodie': 'فوڈیز کے لیے',
    'nav.partner': 'پارٹنرز کے لیے',
    'nav.signIn': 'سائن ان',
    'nav.getStarted': 'شروع کریں',
    'nav.policies': 'پالیسیاں',
    'dash.overview': 'اوور ویو',
    'dash.liveOrders': 'لائیو آرڈرز',
    'dash.menuManager': 'مینو مینیجر',
    'dash.aiAssistant': 'اے آئی اسسٹنٹ',
    'dash.qrBuilder': 'کیو آر بلڈر',
    'dash.settings': 'سیٹنگز',
    'dash.signOut': 'سائن آؤٹ',
    'dash.adminPortal': 'ایڈمن پورٹل',
    'dash.morning': 'صبح بخیر',
    'dash.afternoon': 'دوپہر بخیر',
    'dash.evening': 'شام بخیر',
    'settings.title': 'لائیو میجک کینوس',
    'settings.subtitle': 'اپنے برانڈ کو ڈیزائن کریں اور ریئل ٹائم میں سسٹم آپریشنز کو کنفیگر کریں۔',
    'settings.saveChanges': 'تبدیلیاں محفوظ کریں',
    'settings.profile': 'ریستوراں پروفائل',
    'settings.localization': 'پورٹل کی زبان',
    'settings.security': 'سیکیورٹی اور رسائی',
    'hero.badge': 'وائس AI سے چلتا ہے',
    'hero.badgeText': 'اے آئی وائس آرڈرنگ',
    'hero.headlineMain1': 'بہتر آرڈر کریں۔',
    'hero.headlineMain2': 'آواز سے۔ ذائقے تک۔',
    'hero.watchDemo': 'ڈیمو دیکھیں',
    'hero.liveOrdering': 'لائیو آرڈرنگ',
    'hero.voicePowered': 'آواز سے چلنے والا',
    'hero.instantQR': 'فوری کیو آر',
    'hero.scroll': 'اسکرول',
    'hero.demoVoicePill': '"دو زنگر برگر آرڈر کریں..."',
    'hero.headline1': 'ذائقے میں انقلاب',
    'hero.headline2': 'وائس AI کے ساتھ',
    'hero.subheadline': 'کھانے کی دریافت کے مستقبل کا تجربہ کریں جہاں آپ کی آواز ذاتی نوعیت کے کھانے کے سفر کو کھولتی ہے۔',
    'hero.tryVoice': 'وائس سرچ آزمائیں',
    'about.subtitle': 'سے سیور کے بارے میں',
    'about.title': 'آپ کے کھانے کے تجربے کو بدلنا',
    'about.title1': 'آپ کے کھانے کا',
    'about.title2': 'تجربہ بدلنا',
    'about.description': 'سے سیور جدید ترین وائس AI ٹیکنالوجی کو بہترین کھانے کے شوق کے ساتھ جوڑتا ہے۔',
    'about.learnMore': 'مزید جانیں',
    'about.globalReach': 'عالمی رسائی',
    'about.globalReachDesc': 'دنیا بھر کے ریستوران اور کھانے دریافت کریں۔',
    'about.secure': 'محفوظ اور نجی',
    'about.secureDesc': 'آپ کا ڈیٹا انٹرپرائز گریڈ سیکیورٹی سے محفوظ ہے۔',
    'about.fast': 'بجلی کی رفتار',
    'about.fastDesc': 'ہماری AI انجن سے فوری سفارشات حاصل کریں۔',
    'features.badge': 'طاقتور خصوصیات',
    'features.title': 'آواز سے کھانے کا آرڈر',
    'features.title1': 'سب کے لیے',
    'features.title2': 'بنایا گیا',
    'features.subtitle': 'کھانے کا آرڈر جو آپ کو سمجھتا ہے—آپ کی ثقافت، آپ کی ضروریات۔',
    'features.cultural': 'ثقافتی سمجھ',
    'features.culturalDesc': 'غذائی ترجیحات اور مذہبی تقاضوں کی بنیاد پر ذہین فلٹرنگ۔',
    'features.accessibility': 'عالمگیر رسائی',
    'features.accessibilityDesc': 'WCAG 2.1 AA کے مطابق ہر کسی کے لیے ڈیزائن کیا گیا۔',
    'features.ai': 'جذباتی ذہین AI',
    'features.aiDesc': 'ہماری AI آپ کی ترجیحات سیکھتی ہے۔',
    'features.qr': 'فوری QR آرڈرنگ',
    'features.qrDesc': 'QR کوڈ اسکین کریں اور سیکنڈوں میں آرڈر دیں۔ کوئی ایپ ڈاؤن لوڈ ضروری نہیں۔',
    'features.multilang': 'کثیر لسانی سپورٹ',
    'features.multilangDesc': '50+ زبانوں کی سپورٹ تاکہ ہر گاہک والی گھر محسوس کرے۔',
    'features.analytics': 'سمارٹ اینالٹکس',
    'features.analyticsDesc': 'ریستوران مالکان کو مقبول ڈشز، چوٹی کے اوقات اور گاہکوں کے رویے کی ریئل ٹائم بصیرت ملتی ہے۔',
    'how.subtitle': 'آسان عمل',
    'how.title': 'یہ کیسے کام کرتا ہے',
    'how.step1Title': 'اسکین کریں اور براؤز کریں',
    'how.step1Desc': 'اپنی میز پر QR کوڈ اسکین کریں اور فوری طور پر مکمل ڈیجیٹل مینو تک رسائی حاصل کریں۔',
    'how.step2Title': 'آواز سے آرڈر کریں',
    'how.step2Desc': 'اپنی زبان میں قدرتی طور پر آرڈر بولیں۔ ہماری AI آپ کا لہجہ اور ترجیحات سمجھتی ہے۔',
    'how.step3Title': 'کھانے کا مزہ لیں',
    'how.step3Desc': 'آرام سے بیٹھیں جب آپ کا آرڈر تیار ہو رہا ہو۔ ریئل ٹائم اپڈیٹس آپ کو ہر قدم پر باخبر رکھتی ہیں۔',
    'howItWorks.title': 'یہ کیسے کام کرتا ہے',
    'howItWorks.subtitle': 'آپ کے بہترین کھانے کے لیے تین آسان قدم',
    'howItWorks.step1Title': 'اپنی خواہش بولیں',
    'howItWorks.step1Desc': 'بس ہمیں بتائیں کہ آپ کیا چاہتے ہیں۔ ہماری AI 50+ زبانوں میں سمجھتی ہے۔',
    'howItWorks.step2Title': 'AI آپ کا میچ تلاش کرے',
    'howItWorks.step2Desc': 'ہماری ذہین انجن آپ کی ترجیحات کا تجزیہ کرتی ہے۔',
    'howItWorks.step3Title': 'اپنے کھانے کا لطف اٹھائیں',
    'howItWorks.step3Desc': 'ایک ٹیپ سے آرڈر کریں اور اپنے کھانے کو ٹریک کریں۔',
    'howItWorks.learnMore': 'ہمارے عمل کے بارے میں مزید جانیں',
    'testimonials.title': 'لوگ کیا کہتے ہیں',
    'testimonials.subtitle': 'ہزاروں مطمئن صارفین کی صفوں میں شامل ہوں۔',
    'testimonials.t1Name': 'احمد کریمی',
    'testimonials.t1Role': 'کھانے کا شوقین، تہران',
    'testimonials.t1Text': 'SaySavor نے میرے کھانا آرڈر کرنے کا طریقہ بدل دیا۔ میں بس قدرتی طور پر بولتا ہوں اور یہ مجھے بالکل سمجھ لیتا ہے!',
    'testimonials.t2Name': 'سمیرہ بنالی',
    'testimonials.t2Role': 'ریستوران مالکہ، کازابلانکا',
    'testimonials.t2Text': 'SaySavor کے بعد ہمارے آرڈرز میں 40% اضافہ ہوا۔ اینالٹکس ڈیش بورڈ بہت مفید ہے۔',
    'testimonials.t3Name': 'روی مہتہ',
    'testimonials.t3Role': 'فوڈی اور مسافر، ممبئی',
    'testimonials.t3Text': 'آخر ایک ایسی ایپ ملی جو میری غذائی پابندیوں کا احترام کرتی ہے۔ AI واقعی سمجھتی ہے۔',
    'cta.badge': '500K+ صارفین میں شامل ہوں',
    'cta.title': 'اپنے کھانے کے تجربے کو بدلنے کے لیے تیار ہیں؟',
    'cta.subtitle': 'آج ہی سے سیور ڈاؤن لوڈ کریں۔',
    'cta.description': '500,000 سے زیادہ کھانے کے شوقین افراد کے ساتھ شامل ہوں جو SaySavor سے آرڈر کرتے ہیں۔',
    'cta.getStarted': 'مفت شروع کریں',
    'cta.scheduleDemo': 'ڈیمو شیڈول کریں',
    'cta.downloadNow': 'ابھی ڈاؤن لوڈ کریں',
    'cta.becomePartner': 'پارٹنر بنیں',
    'persona.title': 'اپنا سفر منتخب کریں',
    'persona.title1': 'اپنا',
    'persona.title2': 'سفر منتخب کریں',
    'persona.subtitle': 'چاہے آپ کھانا تلاش کرنے آئے ہوں یا اپنے ریستوران کا کاروبار بڑھانے۔',
    'persona.foodie': 'میں فوڈی ہوں',
    'persona.foodieSubtitle': 'آپ کے لیے بنائے گئے کھانے کے تجربات دریافت کریں',
    'persona.foodieDesc': 'سینکڑوں ریستوران دریافت کریں، اپنی زبان میں آرڈر کریں، اور اپنی غذائی ترجیحات کے مطابق کھانے کا لطف اٹھائیں۔',
    'persona.foodieCta': 'فوڈی کے طور پر دریافت کریں',
    'persona.partner': 'میں پارٹنر ہوں',
    'persona.partnerSubtitle': 'ذہین تجزیات کے ساتھ اپنا ریستوران بڑھائیں',
    'persona.partnerDesc': 'AI سے چلنے والی بصیرت، وائس آرڈرنگ اور ہموار کسٹمر مینجمنٹ سے اپنی آمدنی بڑھائیں۔',
    'persona.partnerCta': 'پارٹنر کے طور پر شامل ہوں',
    'persona.getStarted': 'شروع کریں',
    'persona.exploreNow': 'دریافت کریں',
    'persona.restaurantsCount': '1,200+ ریسٹورنٹس',
    'persona.foodieFeature1': 'اپنی زبان میں وائس آرڈرنگ',
    'persona.foodieFeature2': 'AI کی سفارش کردہ ریستوران',
    'persona.foodieFeature3': 'ثقافتی اور غذائی ترجیحات',
    'persona.foodieFeature4': 'ریئل ٹائم آرڈر ٹریکنگ',
    'persona.partnerFeature1': 'ایڈوانس اینالٹکس ڈیش بورڈ',
    'persona.partnerFeature2': 'AI طلب کی پیشگوئی',
    'persona.partnerFeature3': 'ملٹی چینل آرڈر مینجمنٹ',
    'persona.partnerFeature4': 'کسٹمر بصیرت اور رجحانات',
    'policies.subtitle': 'آپ کے ساتھ ہمارا عہد',
    'footer.description': 'وائس AI ٹیکنالوجی کے ساتھ کھانے کے آرڈر میں انقلاب۔',
    'footer.product': 'پروڈکٹ',
    'footer.company': 'کمپنی',
    'footer.resources': 'وسائل',
    'footer.legal': 'قانونی',
    'footer.copyright': '© 2025 سے سیور۔ تمام حقوق محفوظ ہیں۔',
    'footer.madeWith': 'بنایا گیا',
    'footer.forFoodLovers': 'دنیا بھر کے کھانے کے شوقینوں کے لیے',
    'policies.title': 'قانونی اور پالیسیاں',
    'policies.privacy': 'رازداری کی پالیسی',
    'policies.terms': 'سروس کی شرائط',
    'policies.cookies': 'کوکی پالیسی',
    'policies.partner': 'پارٹنر گائیڈلائنز',
    'policies.heroDescription': 'شفافیت ہمارے لیے اہم ہے۔ یہاں آپ کو ہماری تمام قانونی دستاویزات اور پالیسیاں ملیں گی۔',
    'policies.lastUpdated': 'آخری اپڈیٹ',
    'policies.december2025': 'دسمبر 2025',
    'policies.contactTitle': 'ہماری پالیسیوں کے بارے میں سوالات؟',
    'policies.contactDescription': 'اگر آپ کو ہماری پالیسیوں کے بارے میں کوئی سوال ہے تو براہ کرم ہم سے رابطہ کریں۔',
    'policies.contactButton': 'قانونی ٹیم سے رابطہ کریں',
    'policies.privacyDesc': 'ہم آپ کا ذاتی ڈیٹا کیسے جمع، استعمال اور محفوظ کرتے ہیں۔',
    'policies.infoCollect': 'جو معلومات ہم جمع کرتے ہیں',
    'policies.infoCollectContent': 'ہم وہ معلومات جمع کرتے ہیں جو آپ براہ راست فراہم کرتے ہیں، جیسے اکاؤنٹ کی تفصیلات، آرڈر کی تاریخ۔',
    'policies.howWeUse': 'ہم آپ کی معلومات کا استعمال کیسے کرتے ہیں',
    'policies.howWeUseContent': 'آپ کا ڈیٹا آرڈرز پر عمل کرنے، سفارشات کو ذاتی بنانے، اور آپ سے بات چیت کرنے کے لیے استعمال ہوتا ہے۔',
    'policies.dataSharing': 'ڈیٹا شیئرنگ',
    'policies.dataSharingContent': 'ہم آرڈرز مکمل کرنے کے لیے ریستوران پارٹنرز کے ساتھ ضروری معلومات شیئر کرتے ہیں۔',
    'policies.yourRights': 'آپ کے حقوق',
    'policies.yourRightsContent': 'آپ کو اپنا ڈیٹا دیکھنے، درست کرنے یا حذف کرنے کا حق ہے۔',
    'policies.termsDesc': 'SaySavor استعمال کرنے کی شرائط و ضوابط۔',
    'policies.accountResp': 'اکاؤنٹ کی ذمہ داریاں',
    'policies.accountRespContent': 'آپ اپنے اکاؤنٹ کی سیکیورٹی اور اس کے تحت تمام سرگرمیوں کے ذمہ دار ہیں۔',
    'policies.serviceUsage': 'سروس کا استعمال',
    'policies.serviceUsageContent': 'SaySavor ذاتی، غیر تجارتی فوڈ آرڈرنگ کے لیے فراہم کیا جاتا ہے۔',
    'policies.orderPolicies': 'آرڈر کی پالیسیاں',
    'policies.orderPoliciesContent': 'آرڈرز تصدیق کے بعد پابند ہیں۔ منسوخی کی پالیسیاں ریستوران پارٹنرز طے کرتے ہیں۔',
    'policies.liability': 'ذمہ داری کی حد',
    'policies.liabilityContent': 'SaySavor کھانے کے معیار کے مسائل کا ذمہ دار نہیں ہے۔',
    'policies.cookiesDesc': 'ہم کوکیز اور ٹریکنگ ٹیکنالوجیز کا استعمال کیسے کرتے ہیں۔',
    'policies.essentialCookies': 'ضروری کوکیز',
    'policies.essentialCookiesContent': 'لاگ ان سیشنز اور کارٹ مینجمنٹ جیسی بنیادی فعالیت کے لیے ضروری۔',
    'policies.analyticsCookies': 'تجزیاتی کوکیز',
    'policies.analyticsCookiesContent': 'یہ سمجھنے میں مدد کرتی ہیں کہ صارفین پلیٹ فارم کے ساتھ کیسے تعامل کرتے ہیں۔',
    'policies.prefCookies': 'ترجیحی کوکیز',
    'policies.prefCookiesContent': 'آپ کی سیٹنگز جیسے زبان کی ترجیحات یاد رکھتی ہیں۔',
    'policies.managingCookies': 'کوکیز کا انتظام',
    'policies.managingCookiesContent': 'آپ براؤزر سیٹنگز میں کوکی ترجیحات کا انتظام کر سکتے ہیں۔',
    'policies.partnerDesc': 'ریستوران پارٹنرز کے لیے رہنما اصول۔',
    'policies.qualityStandards': 'معیار کے معیارات',
    'policies.qualityStandardsContent': 'پارٹنرز کو فوڈ سیفٹی معیارات اور درست مینو معلومات برقرار رکھنی چاہیے۔',
    'policies.commission': 'کمیشن کا ڈھانچہ',
    'policies.commissionContent': 'معیاری کمیشن 15-25% فی آرڈر ہے۔',
    'policies.orderFulfillment': 'آرڈر کی تکمیل',
    'policies.orderFulfillmentContent': 'آرڈرز 5 منٹ کے اندر قبول ہونے چاہئیں۔',
    'policies.supportResources': 'سپورٹ وسائل',
    'policies.supportResourcesContent': 'پارٹنرز کو پارٹنر پورٹل اور ڈیڈیکیٹڈ سپورٹ ٹیم تک رسائی ہے۔',
    'policies.privacyB1': 'ڈیٹا جمع کرنے کے طریقے',
    'policies.privacyB2': 'تیسرے فریق سے اشتراک',
    'policies.privacyB3': 'آپ کے حقوق',
    'policies.termsB1': 'صارف کی ذمہ داریاں',
    'policies.termsB2': 'سروس کی حدود',
    'policies.termsB3': 'اکاؤنٹ کی پالیسیاں',
    'policies.cookiesB1': 'کوکی کی اقسام',
    'policies.cookiesB2': 'ترجیحات کا انتظام',
    'policies.cookiesB3': 'تجزیات کا استعمال',
    'policies.partnerB1': 'معیار کے معیارات',
    'policies.partnerB2': 'کمیشن کا ڈھانچہ',
    'policies.partnerB3': 'سپورٹ وسائل',
    'policies.transparencyPriority': 'شفافیت ہماری ترجیح ہے',
    'policies.readMore': 'مزید پڑھیں',
    'about.mission': 'ہمارا مشن',
    'about.missionDesc': 'زبان کی رکاوٹوں کو توڑ کر اور ہر پکوان کو سب کے لیے قابل رسائی بنا کر کھانے کی دریافت کو جمہوری بنانا۔',
    'about.vision': 'ہمارا وژن',
    'about.visionDesc': 'ایک ایسی دنیا جہاں آپ کی آواز ہی وہ واحد چیز ہے جس کی آپ کو بہترین کھانا دریافت کرنے اور لطف اندوز ہونے کے لیے ضرورت ہے۔',
    'about.innovation': 'ہماری جدت',
    'about.innovationDesc': 'بغیر کسی رکاوٹ کے، ثقافتی طور پر باخبر کھانے کے تجربات تخلیق کرنے کے لیے جدید ترین AI اور صوتی شناخت کا استعمال۔',
    'about.storyP1': 'SaySavor ایک سادہ سی الجھن سے پیدا ہوا: غیر ملکی زبان میں کھانا آرڈر کرنا مشکل نہیں ہونا چاہیے۔',
    'about.storyP2': '2025 میں، ہم نے AI محققین، کھانے کے شوقین افراد کی ایک ٹیم بنائی تاکہ ایک ایسا پلیٹ فارم بنایا جا سکے جہاں کوئی بھی اپنی مادری زبان میں کھانا آرڈر کر سکے۔',
    'about.storyP3': 'آج، SaySavor 50 سے زائد ممالک میں 500,000 سے زیادہ صارفین کو خدمات فراہم کرتا ہے۔',
    'about.meetTeam': 'ہماری ٹیم سے ملیں',
    'about.team': 'ٹیم',
    'about.readyToJoin': 'کیا آپ انقلاب میں شامل ہونے کے لیے تیار ہیں؟',
    'about.ctaDesc': 'چاہے آپ کھانے کے شوقین ہوں یا ریستوراں کے پارٹنر، SaySavor میں آپ کے لیے جگہ ہے۔',
    'about.startFoodie': 'بطور فوڈی شروع کریں',
    'about.heroTitle1': 'ہم دنیا کے کھانے',
    'about.heroTitle2': 'دریافت کرنے کا طریقہ بدل رہے ہیں',
    'about.heroDesc': 'ہمارا ماننا ہے کہ بہترین کھانا زبان یا مقام سے قطع نظر سب کے لیے قابل رسائی ہونا چاہیے۔ SaySavor وائس AI کی طاقت سے لوگوں کو ان کے بہترین کھانے سے جوڑنے کے مشن پر ہے۔',
    'about.storyTitle': 'ہماری کہانی',
    'about.statsUsers': 'فعال صارفین',
    'about.statsCountries': 'ممالک',
    'about.statsLangs': 'زبانیں',
    'features.voice': 'سمارٹ وائس سرچ',
    'features.voiceDesc': 'کسی بھی زبان میں قدرتی طور پر بولیں۔ ہماری AI سیاق و سباق، لہجے اور کھانے کی اصطلاحات کو سمجھتی ہے۔',
    'features.realtime': 'ریئل ٹائم اپڈیٹس',
    'features.realtimeDesc': 'لائیو اپڈیٹس، درست ETA اور فوری اطلاعات کے ساتھ کچن سے دروازے تک اپنے آرڈر کو ٹریک کریں۔',
    'features.notifications': 'سمارٹ نوٹیفیکیشنز',
    'features.notifDesc': 'ذاتی نوعیت کے سودے اور آرڈر کی تازہ کاری',
    'features.everythingYou': 'سب کچھ جو آپ کو',
    'features.need': 'چاہیے',
    'features.and': 'اور',
    'features.muchMore': 'بہت کچھ',
    'features.expDiff': 'فرق محسوس کریں',
    'features.joinHundreds': 'ان لاکھوں صارفین میں شامل ہوں جنہوں نے اپنے کھانے کے آرڈرنگ کے تجربے کو بدل دیا ہے۔',
    'howItWorks.startOrdering': 'ابھی آرڈر کرنا شروع کریں',
    'howItWorks.tryYourself': 'کیا آپ خود آزمانے کے لیے تیار ہیں؟',
    'howItWorks.tryDesc': 'آواز سے چلنے والی فوڈ ڈسکوری کا جادو محسوس کریں۔ شروع کرنا بالکل مفت ہے۔',
    'howItWorks.watchDemo': 'ڈیمو ویڈیو دیکھیں',
    'howItWorks.step1Detail1': 'قدرتی زبان کی پروسیسنگ سیاق و سباق کو سمجھتی ہے',
    'howItWorks.step1Detail2': '20+ زبانوں اور بولیوں کی حمایت',
    'howItWorks.step1Detail3': 'لہجے اور تلفظ کی رواداری',
    'howItWorks.step1Detail4': 'شور والے ماحول میں بھی کام کرتا ہے',
    'howItWorks.step2Detail1': 'آپ کے ذائقے کی پروفائل پر مبنی ذاتی نوعیت کا',
    'howItWorks.step2Detail2': 'غذائی اور ثقافتی ترجیحات کے فلٹرز',
    'howItWorks.step2Detail3': 'ریئل ٹائم دستیابی اور انتظار کے اوقات',
    'howItWorks.step2Detail4': 'قیمت کی حد اور فاصلے کی اصلاح',
    'howItWorks.step3Detail1': 'ون ٹیپ یا وائس ایکٹیویٹڈ چیک آؤٹ',
    'howItWorks.step3Detail2': 'GPS کے ساتھ ریئل ٹائم آرڈر ٹریکنگ',
    'howItWorks.step3Detail3': 'ریستوراں کے ساتھ براہ راست رابطہ',
    'howItWorks.step3Detail4': 'درجہ بندی کریں اور اگلی بار کے لیے پسندیدہ محفوظ کریں',
    'features.benefit1v': '20+ زبانیں معاون ہیں',
    'features.benefit2v': 'بولی کی شناخت',
    'features.benefit3v': '90% درستگی کی شرح',
    'features.benefit4v': 'آف لائن موڈ دستیاب ہے',
    'features.benefit1a': 'ذائقہ پروفائل سیکھنا',
    'features.benefit2a': 'موڈ پر مبنی تجاویز',
    'features.benefit3a': 'وقت کے لحاظ سے سفارشات',
    'features.benefit4a': 'پسندیدہ کا خودکار پتہ لگانا',
    'features.benefit1r': 'لائیو GPS ٹریکنگ',
    'features.benefit2r': 'کچن اسٹیٹس کی اپ ڈیٹس',
    'features.benefit3r': 'ڈرائیور سے رابطہ',
    'features.benefit4r': 'درست ETA کی پیشن گوئیاں',
    'foodie.t1Name': 'احمد کے.',
    'foodie.t1Location': 'لاہور',
    'foodie.t1Text': 'آخر کار ایک ایپ جو اردو سمجھتی ہے! گیم چینجر ہے۔',
    'foodie.t2Name': 'سارہ ایم.',
    'foodie.t2Location': 'دبئی',
    'foodie.t2Text': 'حلال فلٹر بہت درست ہے۔ مجھے پسند ہے!',
    'foodie.t3Name': 'جان ڈی.',
    'foodie.t3Location': 'نیویارک',
    'foodie.t3Text': 'ڈرائیونگ کے دوران آواز سے آرڈر کرنا حیرت انگیز ہے۔',
    'scroll.step1Title': 'ڈیجیٹل معدنیات',
    'scroll.step1Heading': 'ایک سینیمیٹک پیشکش',
    'scroll.step1Desc': 'ہمارے پکوانوں کی تھری ڈی رینڈرنگ کا تجربہ کرنے کے لیے اسکرول کریں۔ ہر لذیذ تفصیل دیکھیں۔',
    'scroll.step2Title': 'AI کی درستگی',
    'scroll.step2Heading': 'بہترین تیار کردہ کوڈ',
    'scroll.step2Desc': 'ہمارے اجزاء کی طرح، ہمارے AI الگورتھم بہترین سفارشات کے نتائج کے لیے خاص طور پر منتخب کیے گئے ہیں۔',
    'scroll.step3Title': 'وائس انٹرفیس',
    'scroll.step3Heading': 'اپنی خواہش بولیں',
    'scroll.step3Desc': 'ٹائپنگ کی بالکل ضرورت نہیں۔ نیچرل لینگویج پروسیسنگ سیاق و سباق، بولیوں اور کھانوں کی اصطلاحات کو سمجھتی ہے۔',
    'scroll.step4Heading': 'بولیں اور مزہ لیں۔',
    'scroll.step4Desc': 'ہمارے پلیٹ فارم کو دریافت کرنے کے لیے اسکرول کرنا جاری رکھیں۔',
    'foodie.saveFav': 'پسندیدہ محفوظ کریں',
    'foodie.saveFavDesc': 'پسندیدہ ریستوراں تک فوری رسائی',
    'foodie.easyReorder': 'آسان ری آرڈر',
    'foodie.easyReorderDesc': 'دوبارہ آرڈر کرنے کے لیے ایک ٹیپ',
    'foodie.voiceDemo': 'وائس ڈیمو پیش نظارہ',
    'foodie.lovedBy': 'کی طرف سے پسند کیا گیا',
    'foodie.foodies': 'فوڈیز',
    'foodie.readyOrder': 'آرڈر دینے کے لیے تیار ہیں؟',
    'foodie.join500k': 'ان 500K+ کھانے کے شوقین افراد میں شامل ہوں جو اپنی آواز سے آرڈر کرتے ہیں۔',
    'foodie.getFree': 'مفت شروع کریں',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'عنا',
    'nav.features': 'الميزات',
    'nav.howItWorks': 'كيف يعمل',
    'nav.foodie': 'لعشاق الطعام',
    'nav.partner': 'للشركاء',
    'nav.signIn': 'تسجيل الدخول',
    'nav.getStarted': 'ابدأ الآن',
    'nav.policies': 'السياسات',
    'dash.overview': 'نظرة عامة',
    'dash.liveOrders': 'الطلبات المباشرة',
    'dash.menuManager': 'مدير القائمة',
    'dash.aiAssistant': 'مساعد الذكاء الاصطناعي',
    'dash.qrBuilder': 'منشئ QR',
    'dash.settings': 'الإعدادات',
    'dash.signOut': 'تسجيل الخروج',
    'dash.adminPortal': 'بوابة المسؤول',
    'dash.morning': 'صباح الخير',
    'dash.afternoon': 'مساء الخير',
    'dash.evening': 'مساء الخير',
    'settings.title': 'لوحة السحر الحية',
    'settings.subtitle': 'صمم علامتك التجارية وقم بتكوين عمليات النظام في الوقت الفعلي.',
    'settings.saveChanges': 'حفظ التغييرات',
    'settings.profile': 'ملف مطعم',
    'settings.localization': 'لغة البوابة',
    'settings.security': 'الأمن والوصول',
    'hero.badge': 'تقنية الصوت بالذكاء الاصطناعي',
    'hero.headline1': 'ثورة في الذوق',
    'hero.headline2': 'مع الذكاء الاصطناعي الصوتي',
    'hero.subheadline': 'اختبر مستقبل اكتشاف الطعام حيث يفتح صوتك رحلات طهي مخصصة.',
    'hero.tryVoice': 'جرب البحث الصوتي',
    'about.subtitle': 'عن سي سيفور',
    'about.title': 'تحويل طريقة تجربتك للطعام',
    'about.description': 'سي سيفور يجمع بين تقنية الذكاء الاصطناعي الصوتي المتطورة وشغف الطعام الرائع.',
    'about.learnMore': 'اعرف المزيد',
    'about.globalReach': 'انتشار عالمي',
    'about.globalReachDesc': 'اكتشف المطاعم من جميع أنحاء العالم.',
    'about.secure': 'آمن وخاص',
    'about.secureDesc': 'بياناتك محمية بأمان مؤسسي.',
    'about.fast': 'سريع كالبرق',
    'about.fastDesc': 'احصل على توصيات فورية.',
    'features.badge': 'ميزات قوية',
    'features.title1': 'مصمم',
    'features.title2': 'للجميع',
    'features.subtitle': 'طلب طعام يفهمك—ثقافتك واحتياجاتك.',
    'features.cultural': 'السياق الثقافي',
    'features.culturalDesc': 'تصفية ذكية بناءً على التفضيلات الغذائية والمتطلبات الدينية.',
    'features.accessibility': 'إمكانية الوصول الشاملة',
    'features.accessibilityDesc': 'مصمم للجميع مع الامتثال لـ WCAG 2.1.',
    'features.ai': 'ذكاء اصطناعي عاطفي',
    'features.aiDesc': 'يتعلم الذكاء الاصطناعي تفضيلاتك.',
    'howItWorks.title': 'كيف يعمل',
    'howItWorks.subtitle': 'ثلاث خطوات بسيطة لوجبتك المثالية',
    'howItWorks.step1Title': 'تحدث عن رغبتك',
    'howItWorks.step1Desc': 'أخبرنا ما تريد. يفهم الذكاء الاصطناعي 50+ لغة.',
    'howItWorks.step2Title': 'الذكاء الاصطناعي يجد تطابقك',
    'howItWorks.step2Desc': 'يحلل محركنا الذكي تفضيلاتك.',
    'howItWorks.step3Title': 'استمتع بوجبتك',
    'howItWorks.step3Desc': 'اطلب بنقرة واحدة وتتبع طعامك.',
    'howItWorks.learnMore': 'تعرف على المزيد عن عمليتنا',
    'testimonials.title': 'ماذا يقول الناس',
    'testimonials.subtitle': 'انضم إلى آلاف المستخدمين الراضين.',
    'cta.badge': 'انضم إلى 500K+ مستخدم',
    'cta.title': 'مستعد لتحويل تجربتك الغذائية؟',
    'cta.subtitle': 'حمل سي سيفور اليوم.',
    'cta.downloadNow': 'حمل الآن',
    'cta.becomePartner': 'كن شريكًا',
    'persona.title1': 'اختر',
    'persona.title2': 'رحلتك',
    'persona.subtitle': 'سواء كنت هنا لاكتشاف الطعام أو تنمية مطعمك.',
    'persona.foodie': 'أنا عاشق طعام',
    'persona.foodieSubtitle': 'اكتشف تجارب طهي مصممة لك',
    'persona.partner': 'أنا شريك',
    'persona.partnerSubtitle': 'طور مطعمك بتحليلات ذكية',
    'persona.getStarted': 'ابدأ الآن',
    'persona.exploreNow': 'استكشف الآن',
    'persona.foodieFeature1': 'طلب صوتي بلغتك',
    'persona.foodieFeature2': 'توصيات مطاعم بالذكاء الاصطناعي',
    'persona.foodieFeature3': 'تصفية التفضيلات الثقافية والغذائية',
    'persona.foodieFeature4': 'تتبع الطلب في الوقت الفعلي',
    'persona.partnerFeature1': 'لوحة تحليلات متقدمة',
    'persona.partnerFeature2': 'توقع الطلب بالذكاء الاصطناعي',
    'persona.partnerFeature3': 'إدارة طلبات متعددة القنوات',
    'persona.partnerFeature4': 'رؤى واتجاهات العملاء',
    'footer.description': 'ثورة في طلب الطعام بتقنية الصوت.',
    'footer.product': 'المنتج',
    'footer.company': 'الشركة',
    'footer.resources': 'الموارد',
    'footer.legal': 'قانوني',
    'footer.copyright': '© 2025 سي سيفور. جميع الحقوق محفوظة.',
    'footer.madeWith': 'صنع بـ',
    'footer.forFoodLovers': 'لعشاق الطعام حول العالم',
    'policies.title': 'القانونية والسياسات',
    'policies.privacy': 'سياسة الخصوصية',
    'policies.terms': 'شروط الخدمة',
    'policies.cookies': 'سياسة ملفات تعريف الارتباط',
    'policies.partner': 'إرشادات الشركاء',
    'policies.heroDescription': 'الشفافية مهمة بالنسبة لنا. ستجد هنا جميع وثائقنا القانونية وسياساتنا.',
    'policies.lastUpdated': 'آخر تحديث',
    'policies.december2025': 'ديسمبر 2025',
    'policies.contactTitle': 'أسئلة حول سياساتنا؟',
    'policies.contactDescription': 'إذا كان لديك أي أسئلة حول سياساتنا، فلا تتردد في الاتصال بنا.',
    'policies.contactButton': 'اتصل بالفريق القانوني',
    'policies.privacyDesc': 'كيف نجمع ونستخدم ونحمي بياناتك الشخصية.',
    'policies.infoCollect': 'المعلومات التي نجمعها',
    'policies.infoCollectContent': 'نجمع المعلومات التي تقدمها مباشرة، مثل تفاصيل الحساب وسجل الطلبات.',
    'policies.howWeUse': 'كيف نستخدم معلوماتك',
    'policies.howWeUseContent': 'تُستخدم بياناتك لمعالجة الطلبات وتخصيص التوصيات والتواصل معك.',
    'policies.dataSharing': 'مشاركة البيانات',
    'policies.dataSharingContent': 'نشارك المعلومات الضرورية مع شركاء المطاعم لتنفيذ الطلبات.',
    'policies.yourRights': 'حقوقك',
    'policies.yourRightsContent': 'لديك الحق في الوصول إلى بياناتك أو تصحيحها أو حذفها.',
    'policies.termsDesc': 'شروط وأحكام استخدام SaySavor.',
    'policies.accountResp': 'مسؤوليات الحساب',
    'policies.accountRespContent': 'أنت مسؤول عن الحفاظ على أمان حسابك وجميع الأنشطة تحت حسابك.',
    'policies.serviceUsage': 'استخدام الخدمة',
    'policies.serviceUsageContent': 'يتم توفير SaySavor لطلب الطعام الشخصي غير التجاري.',
    'policies.orderPolicies': 'سياسات الطلب',
    'policies.orderPoliciesContent': 'الطلبات ملزمة بمجرد تأكيدها. تحدد سياسات الإلغاء من قبل شركاء المطاعم.',
    'policies.liability': 'حدود المسؤولية',
    'policies.liabilityContent': 'SaySavor ليست مسؤولة عن مشاكل جودة الطعام.',
    'policies.cookiesDesc': 'كيف نستخدم ملفات تعريف الارتباط وتقنيات التتبع.',
    'policies.essentialCookies': 'ملفات تعريف الارتباط الأساسية',
    'policies.essentialCookiesContent': 'مطلوبة للوظائف الأساسية مثل جلسات تسجيل الدخول.',
    'policies.analyticsCookies': 'ملفات تعريف الارتباط التحليلية',
    'policies.analyticsCookiesContent': 'تساعدنا على فهم كيفية تفاعل المستخدمين مع منصتنا.',
    'policies.prefCookies': 'ملفات تعريف الارتباط المفضلة',
    'policies.prefCookiesContent': 'تتذكر إعداداتك مثل تفضيلات اللغة.',
    'policies.managingCookies': 'إدارة ملفات تعريف الارتباط',
    'policies.managingCookiesContent': 'يمكنك إدارة تفضيلات ملفات تعريف الارتباط في إعدادات المتصفح.',
    'policies.partnerDesc': 'إرشادات لشركاء المطاعم.',
    'policies.qualityStandards': 'معايير الجودة',
    'policies.qualityStandardsContent': 'يجب على الشركاء الحفاظ على معايير سلامة الغذاء.',
    'policies.commission': 'هيكل العمولة',
    'policies.commissionContent': 'العمولة القياسية 15-25% لكل طلب.',
    'policies.orderFulfillment': 'تنفيذ الطلب',
    'policies.orderFulfillmentContent': 'يجب قبول الطلبات في غضون 5 دقائق.',
    'policies.supportResources': 'موارد الدعم',
    'policies.supportResourcesContent': 'يتمتع الشركاء بالوصول إلى بوابة الشركاء وفريق الدعم.',
    'about.title1': 'تحويل طريقة',
    'about.title2': 'تجربتك مع الطعام',
    'features.title': 'طلب الطعام بالصوت',
    'features.qr': 'طلب QR الفوري',
    'features.qrDesc': 'امسح رمز QR وضع طلبك في ثوان.',
    'features.multilang': 'دعم متعدد اللغات',
    'features.multilangDesc': 'دعم 50+ لغة حتى يشعر كل عميل بالراحة.',
    'features.analytics': 'تحليلات ذكية',
    'features.analyticsDesc': 'رؤى فورية حول الأطباق الشهيرة وسلوك العملاء.',
    'how.subtitle': 'عملية بسيطة',
    'how.title': 'كيف يعمل',
    'how.step1Title': 'امسح وتصفح',
    'how.step1Desc': 'امسح رمز QR على طاولتك للوصول الفوري إلى القائمة.',
    'how.step2Title': 'اطلب بالصوت',
    'how.step2Desc': 'تحدث بلغتك بشكل طبيعي. يفهم الذكاء الاصطناعي لهجتك وتفضيلاتك.',
    'how.step3Title': 'استمتع بوجبتك',
    'how.step3Desc': 'استرح بينما يتم تحضير طلبك مع تحديثات فورية.',
    'testimonials.t1Name': 'أحمد کریمی',
    'testimonials.t1Role': 'عاشق طعام، طهران',
    'testimonials.t1Text': 'غيّر SaySavor طريقة طلبي للطعام. أتحدث بشكل طبيعي ويفهمني تماماً!',
    'testimonials.t2Name': 'سميرة بنالي',
    'testimonials.t2Role': 'صاحبة مطعم، الدار البيضاء',
    'testimonials.t2Text': 'منذ دمج SaySavor زادت طلبياتنا بنسبة 40%. تحليلات رائعة.',
    'testimonials.t3Name': 'رافي ميهتا',
    'testimonials.t3Role': 'عاشق طعام ومسافر، مومباي',
    'testimonials.t3Text': 'أخيراً تطبيق يحترم قيودي الغذائية. الذكاء الاصطناعي يفهم حقاً!',
    'cta.description': 'انضم إلى أكثر من 500,000 شخص يستخدمون SaySavor.',
    'cta.getStarted': 'ابدأ مجاناً',
    'cta.scheduleDemo': 'جدول عرضي',
    'persona.title': 'اختر رحلتك',
    'persona.foodieDesc': 'اكتشف مئات المطاعم واطلب بلغتك.',
    'persona.foodieCta': 'استكشف كعاشق طعام',
    'persona.partnerDesc': 'زد إيراداتك بالذكاء الاصطناعي والطلب الصوتي.',
    'persona.partnerCta': 'انضم كشريك',
    'policies.subtitle': 'التزامنا بك',
    'policies.transparencyPriority': 'الشفافية أولويتنا',
    'policies.readMore': 'اقرأ المزيد',
    'policies.privacyB1': 'ممارسات جمع البيانات',
    'policies.privacyB2': 'مشاركة جهة خارجية',
    'policies.privacyB3': 'حقوقك',
    'policies.termsB1': 'مسؤوليات المستخدم',
    'policies.termsB2': 'قيود الخدمة',
    'policies.termsB3': 'سياسات الحساب',
    'policies.cookiesB1': 'أنواع ملفات تعريف الارتباط',
    'policies.cookiesB2': 'إدارة التفضيلات',
    'policies.cookiesB3': 'استخدام التحليلات',
    'policies.partnerB1': 'معايير الجودة',
    'policies.partnerB2': 'هيكل العمولة',
    'policies.partnerB3': 'موارد الدعم',
  },
  hi: {
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.features': 'विशेषताएं',
    'nav.howItWorks': 'यह कैसे काम करता है',
    'nav.foodie': 'फूडीज के लिए',
    'nav.partner': 'पार्टनर्स के लिए',
    'nav.signIn': 'साइन इन',
    'nav.getStarted': 'शुरू करें',
    'nav.policies': 'नीतियाँ',
    'dash.overview': 'अवलोकन',
    'dash.liveOrders': 'लाइव ऑर्डर',
    'dash.menuManager': 'मेनू मैनेजर',
    'dash.aiAssistant': 'एआई सहायक',
    'dash.qrBuilder': 'क्यूआर बिल्डर',
    'dash.settings': 'सेटिंग्स',
    'dash.signOut': 'साइन आउट',
    'dash.adminPortal': 'एडमिन पोर्टल',
    'dash.morning': 'सुप्रभात',
    'dash.afternoon': 'नमस्कार',
    'dash.evening': 'शुभ संध्या',
    'settings.title': 'लाइव मैजिक कैनवास',
    'settings.subtitle': 'अपने ब्रांड को डिज़ाइन करें और रीयल-टाइम में सिस्टम संचालन कॉन्फ़िगर करें।',
    'settings.saveChanges': 'परिवर्तन सहेजें',
    'settings.profile': 'रेस्तरां प्रोफ़ाइल',
    'settings.localization': 'पोर्टल भाषा',
    'settings.security': 'सुरक्षा और पहुंच',
    'hero.badge': 'AI-संचालित वॉइस तकनीक',
    'hero.headline1': 'स्वाद में क्रांति',
    'hero.headline2': 'वॉइस AI के साथ',
    'hero.subheadline': 'भोजन की खोज के भविष्य का अनुभव करें जहां आपकी आवाज व्यक्तिगत पाक यात्राओं को खोलती है।',
    'hero.tryVoice': 'वॉइस सर्च आज़माएं',
    'about.subtitle': 'सेसेवर के बारे में',
    'about.title': 'आपके भोजन अनुभव को बदलना',
    'about.description': 'सेसेवर अत्याधुनिक वॉइस AI तकनीक को शानदार भोजन के जुनून के साथ जोड़ता है।',
    'about.learnMore': 'और जानें',
    'about.globalReach': 'वैश्विक पहुंच',
    'about.globalReachDesc': 'दुनिया भर के रेस्तरां खोजें।',
    'about.secure': 'सुरक्षित और निजी',
    'about.secureDesc': 'आपका डेटा एंटरप्राइज सुरक्षा से सुरक्षित है।',
    'about.fast': 'बिजली की तेज़ी',
    'about.fastDesc': 'तुरंत सिफारिशें प्राप्त करें।',
    'features.badge': 'शक्तिशाली विशेषताएं',
    'features.title1': 'सभी के लिए',
    'features.title2': 'बनाया गया',
    'features.subtitle': 'भोजन ऑर्डरिंग जो आपको समझती है—आपकी संस्कृति, आपकी जरूरतें।',
    'features.cultural': 'सांस्कृतिक समझ',
    'features.culturalDesc': 'आहार वरीयताओं और धार्मिक आवश्यकताओं के आधार पर बुद्धिमान फ़िल्टरिंग।',
    'features.accessibility': 'सार्वभौमिक पहुंच',
    'features.accessibilityDesc': 'WCAG 2.1 AA अनुपालन के साथ सभी के लिए डिज़ाइन किया गया।',
    'features.ai': 'भावनात्मक बुद्धिमान AI',
    'features.aiDesc': 'हमारी AI आपकी वरीयताएं सीखती है।',
    'howItWorks.title': 'यह कैसे काम करता है',
    'howItWorks.subtitle': 'आपके बेहतरीन भोजन के लिए तीन आसान कदम',
    'howItWorks.step1Title': 'अपनी इच्छा बोलें',
    'howItWorks.step1Desc': 'बस हमें बताएं कि आप क्या चाहते हैं। हमारी AI 50+ भाषाएं समझती है।',
    'howItWorks.step2Title': 'AI आपका मैच ढूंढे',
    'howItWorks.step2Desc': 'हमारा बुद्धिमान इंजन आपकी वरीयताओं का विश्लेषण करता है।',
    'howItWorks.step3Title': 'अपने भोजन का आनंद लें',
    'howItWorks.step3Desc': 'एक टैप से ऑर्डर करें और अपने भोजन को ट्रैक करें।',
    'howItWorks.learnMore': 'हमारी प्रक्रिया के बारे में और जानें',
    'testimonials.title': 'लोग क्या कहते हैं',
    'testimonials.subtitle': 'हजारों संतुष्ट उपयोगकर्ताओं में शामिल हों।',
    'cta.badge': '500K+ उपयोगकर्ताओं में शामिल हों',
    'cta.title': 'अपने भोजन अनुभव को बदलने के लिए तैयार हैं?',
    'cta.subtitle': 'आज ही सेसेवर डाउनलोड करें।',
    'cta.downloadNow': 'अभी डाउनलोड करें',
    'cta.becomePartner': 'पार्टनर बनें',
    'persona.title1': 'अपना',
    'persona.title2': 'सफर चुनें',
    'persona.subtitle': 'चाहे आप भोजन खोजने आए हों या अपना रेस्तरां बढ़ाने।',
    'persona.foodie': 'मैं फूडी हूं',
    'persona.foodieSubtitle': 'आपके लिए बनाए गए पाक अनुभव खोजें',
    'persona.partner': 'मैं पार्टनर हूं',
    'persona.partnerSubtitle': 'बुद्धिमान विश्लेषिकी से अपना रेस्तरां बढ़ाएं',
    'persona.getStarted': 'शुरू करें',
    'persona.exploreNow': 'खोजें',
    'persona.foodieFeature1': 'अपनी भाषा में वॉइस ऑर्डरिंग',
    'persona.foodieFeature2': 'AI-क्यूरेटेड रेस्तरां सिफारिशें',
    'persona.foodieFeature3': 'सांस्कृतिक और आहार वरीयता फ़िल्टरिंग',
    'persona.foodieFeature4': 'रियल-टाइम ऑर्डर ट्रैकिंग',
    'persona.partnerFeature1': 'उन्नत विश्लेषिकी डैशबोर्ड',
    'persona.partnerFeature2': 'AI-संचालित मांग पूर्वानुमान',
    'persona.partnerFeature3': 'मल्टी-चैनल ऑर्डर प्रबंधन',
    'persona.partnerFeature4': 'ग्राहक अंतर्दृष्टि और रुझान',
    'footer.description': 'वॉइस AI तकनीक से भोजन ऑर्डरिंग में क्रांति।',
    'footer.product': 'उत्पाद',
    'footer.company': 'कंपनी',
    'footer.resources': 'संसाधन',
    'footer.legal': 'कानूनी',
    'footer.copyright': '© 2025 सेसेवर। सर्वाधिकार सुरक्षित।',
    'footer.madeWith': 'बनाया गया',
    'footer.forFoodLovers': 'दुनिया भर के खाने के शौकीनों के लिए',
    'policies.title': 'कानूनी और नीतियां',
    'policies.privacy': 'गोपनीयता नीति',
    'policies.terms': 'सेवा की शर्तें',
    'policies.cookies': 'कुकी नीति',
    'policies.partner': 'पार्टनर दिशानिर्देश',
    'policies.heroDescription': 'पारदर्शिता हमारे लिए महत्वपूर्ण है। यहां आपको हमारे सभी कानूनी दस्तावेज़ और नीतियां मिलेंगी।',
    'policies.lastUpdated': 'अंतिम अपडेट',
    'policies.december2025': 'दिसंबर 2025',
    'policies.contactTitle': 'हमारी नीतियों के बारे में प्रश्न?',
    'policies.contactDescription': 'यदि आपके पास हमारी नीतियों के बारे में कोई प्रश्न है, तो कृपया हमसे संपर्क करें।',
    'policies.contactButton': 'कानूनी टीम से संपर्क करें',
    'policies.privacyDesc': 'हम आपका व्यक्तिगत डेटा कैसे एकत्र, उपयोग और सुरक्षित करते हैं।',
    'policies.infoCollect': 'हम कौन सी जानकारी एकत्र करते हैं',
    'policies.infoCollectContent': 'हम वह जानकारी एकत्र करते हैं जो आप सीधे प्रदान करते हैं, जैसे खाता विवरण, ऑर्डर इतिहास।',
    'policies.howWeUse': 'हम आपकी जानकारी का उपयोग कैसे करते हैं',
    'policies.howWeUseContent': 'आपका डेटा ऑर्डर प्रोसेस करने, सिफारिशें व्यक्तिगत करने और आपसे संवाद करने के लिए उपयोग होता है।',
    'policies.dataSharing': 'डेटा साझाकरण',
    'policies.dataSharingContent': 'हम ऑर्डर पूरा करने के लिए रेस्तरां पार्टनर्स के साथ आवश्यक जानकारी साझा करते हैं।',
    'policies.yourRights': 'आपके अधिकार',
    'policies.yourRightsContent': 'आपको अपना डेटा एक्सेस करने, सही करने या हटाने का अधिकार है।',
    'policies.termsDesc': 'SaySavor उपयोग करने की शर्तें और नियम।',
    'policies.accountResp': 'खाता जिम्मेदारियां',
    'policies.accountRespContent': 'आप अपने खाते की सुरक्षा और उसके तहत सभी गतिविधियों के लिए जिम्मेदार हैं।',
    'policies.serviceUsage': 'सेवा उपयोग',
    'policies.serviceUsageContent': 'SaySavor व्यक्तिगत, गैर-वाणिज्यिक फूड ऑर्डरिंग के लिए प्रदान किया जाता है।',
    'policies.orderPolicies': 'ऑर्डर नीतियां',
    'policies.orderPoliciesContent': 'ऑर्डर पुष्टि के बाद बाध्यकारी हैं। रद्द करने की नीतियां रेस्तरां पार्टनर्स तय करते हैं।',
    'policies.liability': 'दायित्व की सीमा',
    'policies.liabilityContent': 'SaySavor भोजन गुणवत्ता के मुद्दों के लिए उत्तरदायी नहीं है।',
    'policies.cookiesDesc': 'हम कुकीज़ और ट्रैकिंग तकनीकों का उपयोग कैसे करते हैं।',
    'policies.essentialCookies': 'आवश्यक कुकीज़',
    'policies.essentialCookiesContent': 'लॉगिन सत्र और कार्ट प्रबंधन जैसी बुनियादी कार्यक्षमता के लिए आवश्यक।',
    'policies.analyticsCookies': 'एनालिटिक्स कुकीज़',
    'policies.analyticsCookiesContent': 'यह समझने में मदद करती हैं कि उपयोगकर्ता प्लेटफ़ॉर्म के साथ कैसे इंटरैक्ट करते हैं।',
    'policies.prefCookies': 'वरीयता कुकीज़',
    'policies.prefCookiesContent': 'आपकी सेटिंग्स जैसे भाषा वरीयताएँ याद रखती हैं।',
    'policies.managingCookies': 'कुकीज़ प्रबंधन',
    'policies.managingCookiesContent': 'आप ब्राउज़र सेटिंग्स में कुकी वरीयताएँ प्रबंधित कर सकते हैं।',
    'policies.partnerDesc': 'रेस्तरां पार्टनर्स के लिए दिशानिर्देश।',
    'policies.qualityStandards': 'गुणवत्ता मानक',
    'policies.qualityStandardsContent': 'पार्टनर्स को खाद्य सुरक्षा मानकों और सटीक मेनू जानकारी बनाए रखनी चाहिए।',
    'policies.commission': 'कमीशन संरचना',
    'policies.commissionContent': 'मानक कमीशन 15-25% प्रति ऑर्डर है।',
    'policies.orderFulfillment': 'ऑर्डर पूर्ति',
    'policies.orderFulfillmentContent': 'ऑर्डर 5 मिनट के भीतर स्वीकार किए जाने चाहिए।',
    'policies.supportResources': 'सहायता संसाधन',
    'policies.supportResourcesContent': 'पार्टनर्स को पार्टनर पोर्टल और समर्पित सहायता टीम तक पहुंच है।',
    'about.title1': 'आपका भोजन',
    'about.title2': 'अनुभव बदलना',
    'features.title': 'आवाज से भोजन ऑर्डर',
    'features.qr': 'इंस्टेंट QR ऑर्डरिंग',
    'features.qrDesc': 'QR कोड स्कैन करें और सेकंडों में ऑर्डर दें।',
    'features.multilang': 'बहुभाषी समर्थन',
    'features.multilangDesc': '50+ भाषाओं का समर्थन।',
    'features.analytics': 'स्मार्ट विश्लेषिकी',
    'features.analyticsDesc': 'रेस्तरां मालिकों को रील-टाइम अंतर्दृष्टि।',
    'how.subtitle': 'सरल प्रक्रिया',
    'how.title': 'यह कैसे काम करता है',
    'how.step1Title': 'स्कैन करें और ब्राउज़ करें',
    'how.step1Desc': 'अपनी मेज़ पर QR कोड स्कैन करें और मेनू देखें।',
    'how.step2Title': 'आवाज से ऑर्डर दें',
    'how.step2Desc': 'अपनी भाषा में बोलीबॉलकर ऑर्डर दें। एआई आपकी बोली समझती है।',
    'how.step3Title': 'अपने भोजन का आनंद लें',
    'how.step3Desc': 'आराम से बैठें जब आपका ऑर्डर तैयार हो रहा हो।',
    'testimonials.t1Name': 'अहमद करीमी',
    'testimonials.t1Role': 'भोजन प्रेमी, तेहरान',
    'testimonials.t1Text': 'SaySavor ने मेरे भोजन ऑर्डर का तरीका बदल दिया!',
    'testimonials.t2Name': 'समिरा बेनाली',
    'testimonials.t2Role': 'रेस्तरां मालिक, कासाब्लांका',
    'testimonials.t2Text': 'SaySavor के बाद हमारे ऑर्डर 40% बढ़े।',
    'testimonials.t3Name': 'रवि मेहता',
    'testimonials.t3Role': 'फूडी और यात्री, मुंबई',
    'testimonials.t3Text': 'अंततः एक ऐप है जो मेरी खाद्य पाबंदियों का सम्मान करता है!',
    'cta.description': '500,000 से अधिक भोजन प्रेमियों के साथ जुड़ें।',
    'cta.getStarted': 'मुफ़्‍त शुरू करें',
    'cta.scheduleDemo': 'डेमो शेड्यूल करें',
    'persona.title': 'अपनी यात्रा चुनें',
    'persona.foodieDesc': 'सैकड़ों रेस्तरां खोजें और अपनी भाषा में ऑर्डर करें।',
    'persona.foodieCta': 'फूडी के रूप में खोजें',
    'persona.partnerDesc': 'AI से अपनी आमदनी बढ़ाएं।',
    'persona.partnerCta': 'पार्टनर के रूप में जुड़ें',
    'policies.subtitle': 'आपके प्रति हमारी प्रतिबद्धता',
    'policies.transparencyPriority': 'पारदर्शिता हमारी प्राथमिकता',
    'policies.readMore': 'और पढ़ें',
    'policies.privacyB1': 'डेटा संग्रहण अभ्यास',
    'policies.privacyB2': 'तृतीय पक्ष साझाकरण',
    'policies.privacyB3': 'आपके अधिकार',
    'policies.termsB1': 'उपयोगकर्ता जिम्मेदारियां',
    'policies.termsB2': 'सेवा सीमाएं',
    'policies.termsB3': 'खाता नीतियां',
    'policies.cookiesB1': 'कुकी प्रकार',
    'policies.cookiesB2': 'प्राथमिकताओं का प्रबंधन',
    'policies.cookiesB3': 'विश्लेषिकी उपयोग',
    'policies.partnerB1': 'गुणवत्ता मानक',
    'policies.partnerB2': 'कमीशन संरचना',
    'policies.partnerB3': 'सहायता संसाधन',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.features': 'Características',
    'nav.howItWorks': 'Cómo Funciona',
    'nav.foodie': 'Para Foodies',
    'nav.partner': 'Para Socios',
    'nav.signIn': 'Iniciar Sesión',
    'nav.getStarted': 'Empezar',
    'nav.policies': 'Políticas',
    'dash.overview': 'Resumen',
    'dash.liveOrders': 'Pedidos en vivo',
    'dash.menuManager': 'Gestor de menú',
    'dash.aiAssistant': 'Asistente IA',
    'dash.qrBuilder': 'Constructor QR',
    'dash.settings': 'Ajustes',
    'dash.signOut': 'Cerrar sesión',
    'dash.adminPortal': 'Panel de administración',
    'dash.morning': 'Buenos Días',
    'dash.afternoon': 'Buenas Tardes',
    'dash.evening': 'Buenas Noches',
    'settings.title': 'Lienzo Mágico en Vivo',
    'settings.subtitle': 'Diseñe su marca y configure las operaciones del sistema en tiempo real.',
    'settings.saveChanges': 'Guardar cambios',
    'settings.profile': 'Perfil del restaurante',
    'settings.localization': 'Idioma del portal',
    'settings.security': 'Seguridad y acceso',
    'hero.badge': 'Tecnología de Voz con IA',
    'hero.headline1': 'Revolucionando el Sabor',
    'hero.headline2': 'con IA de Voz',
    'hero.subheadline': 'Experimenta el futuro del descubrimiento gastronómico donde tu voz desbloquea viajes culinarios personalizados.',
    'hero.tryVoice': 'Probar Búsqueda por Voz',
    'about.subtitle': 'Sobre SaySavor',
    'about.title': 'Transformando Tu Experiencia Gastronómica',
    'about.description': 'SaySavor combina tecnología de voz AI de vanguardia con pasión por la buena comida.',
    'about.learnMore': 'Saber Más',
    'about.globalReach': 'Alcance Global',
    'about.globalReachDesc': 'Descubre restaurantes de todo el mundo.',
    'about.secure': 'Seguro y Privado',
    'about.secureDesc': 'Tus datos están protegidos con seguridad empresarial.',
    'about.fast': 'Rápido como un Rayo',
    'about.fastDesc': 'Obtén recomendaciones instantáneas.',
    'features.badge': 'Características Poderosas',
    'features.title1': 'Diseñado para',
    'features.title2': 'Todos',
    'features.subtitle': 'Pedidos de comida que te entienden—tu cultura, tus necesidades.',
    'features.cultural': 'Contextualización Cultural',
    'features.culturalDesc': 'Filtrado inteligente basado en preferencias dietéticas y requisitos religiosos.',
    'features.accessibility': 'Accesibilidad Universal',
    'features.accessibilityDesc': 'Diseñado para todos con cumplimiento WCAG 2.1.',
    'features.ai': 'IA Emocionalmente Inteligente',
    'features.aiDesc': 'Nuestra IA aprende tus preferencias.',
    'howItWorks.title': 'Cómo Funciona',
    'howItWorks.subtitle': 'Tres simples pasos para tu comida perfecta',
    'howItWorks.step1Title': 'Di Tu Antojo',
    'howItWorks.step1Desc': 'Simplemente dinos qué quieres. Nuestra IA entiende 50+ idiomas.',
    'howItWorks.step2Title': 'La IA Encuentra Tu Match',
    'howItWorks.step2Desc': 'Nuestro motor inteligente analiza tus preferencias.',
    'howItWorks.step3Title': 'Disfruta Tu Comida',
    'howItWorks.step3Desc': 'Ordena con un toque y rastrea tu comida.',
    'howItWorks.learnMore': 'Aprende más sobre nuestro proceso',
    'testimonials.title': 'Lo Que Dice la Gente',
    'testimonials.subtitle': 'Únete a miles de usuarios satisfechos.',
    'cta.badge': 'Únete a 500K+ Usuarios',
    'cta.title': '¿Listo para Transformar Tu Experiencia Gastronómica?',
    'cta.subtitle': 'Descarga SaySavor hoy.',
    'cta.downloadNow': 'Descargar Ahora',
    'cta.becomePartner': 'Ser Socio',
    'persona.title1': 'Elige Tu',
    'persona.title2': 'Camino',
    'persona.subtitle': 'Ya sea que estés aquí para descubrir comida o hacer crecer tu restaurante.',
    'persona.foodie': 'Soy un Foodie',
    'persona.foodieSubtitle': 'Descubre experiencias culinarias diseñadas para ti',
    'persona.partner': 'Soy un Socio',
    'persona.partnerSubtitle': 'Haz crecer tu restaurante con análisis inteligentes',
    'persona.getStarted': 'Empezar',
    'persona.exploreNow': 'Explorar Ahora',
    'persona.foodieFeature1': 'Pedidos por voz en tu idioma',
    'persona.foodieFeature2': 'Recomendaciones de restaurantes con IA',
    'persona.foodieFeature3': 'Filtrado de preferencias culturales y dietéticas',
    'persona.foodieFeature4': 'Seguimiento de pedidos en tiempo real',
    'persona.partnerFeature1': 'Panel de análisis avanzado',
    'persona.partnerFeature2': 'Previsión de demanda con IA',
    'persona.partnerFeature3': 'Gestión de pedidos multicanal',
    'persona.partnerFeature4': 'Insights y tendencias de clientes',
    'footer.description': 'Revolucionando los pedidos de comida con tecnología de voz IA.',
    'footer.product': 'Producto',
    'footer.company': 'Empresa',
    'footer.resources': 'Recursos',
    'footer.legal': 'Legal',
    'footer.copyright': '© 2025 SaySavor. Todos los derechos reservados.',
    'footer.madeWith': 'Hecho con',
    'footer.forFoodLovers': 'para amantes de la comida en todo el mundo',
    'policies.title': 'Legal y Políticas',
    'policies.privacy': 'Política de Privacidad',
    'policies.terms': 'Términos de Servicio',
    'policies.cookies': 'Política de Cookies',
    'policies.partner': 'Guías para Socios',
    'policies.heroDescription': 'La transparencia es importante para nosotros. Aquí encontrarás todos nuestros documentos legales y políticas.',
    'policies.lastUpdated': 'Última actualización',
    'policies.december2025': 'Diciembre 2025',
    'policies.contactTitle': '¿Preguntas sobre nuestras políticas?',
    'policies.contactDescription': 'Si tiene alguna pregunta sobre nuestras políticas, no dude en contactarnos.',
    'policies.contactButton': 'Contactar al equipo legal',
    'policies.privacyDesc': 'Cómo recopilamos, usamos y protegemos sus datos personales.',
    'policies.infoCollect': 'Información que recopilamos',
    'policies.infoCollectContent': 'Recopilamos información que proporciona directamente, como detalles de cuenta e historial de pedidos.',
    'policies.howWeUse': 'Cómo usamos su información',
    'policies.howWeUseContent': 'Sus datos se utilizan para procesar pedidos, personalizar recomendaciones y comunicarnos con usted.',
    'policies.dataSharing': 'Compartir datos',
    'policies.dataSharingContent': 'Compartimos información necesaria con socios de restaurantes para cumplir pedidos.',
    'policies.yourRights': 'Sus derechos',
    'policies.yourRightsContent': 'Tiene derecho a acceder, corregir o eliminar sus datos.',
    'policies.termsDesc': 'Términos y condiciones para usar SaySavor.',
    'policies.accountResp': 'Responsabilidades de la cuenta',
    'policies.accountRespContent': 'Usted es responsable de mantener la seguridad de su cuenta y todas las actividades bajo ella.',
    'policies.serviceUsage': 'Uso del servicio',
    'policies.serviceUsageContent': 'SaySavor se proporciona para pedidos de comida personales, no comerciales.',
    'policies.orderPolicies': 'Políticas de pedidos',
    'policies.orderPoliciesContent': 'Los pedidos son vinculantes una vez confirmados. Las políticas de cancelación las establecen los socios.',
    'policies.liability': 'Limitación de responsabilidad',
    'policies.liabilityContent': 'SaySavor no es responsable de problemas de calidad de alimentos.',
    'policies.cookiesDesc': 'Cómo usamos cookies y tecnologías de seguimiento.',
    'policies.essentialCookies': 'Cookies esenciales',
    'policies.essentialCookiesContent': 'Requeridas para funcionalidad básica como sesiones de inicio.',
    'policies.analyticsCookies': 'Cookies de análisis',
    'policies.analyticsCookiesContent': 'Nos ayudan a entender cómo interactúan los usuarios con la plataforma.',
    'policies.prefCookies': 'Cookies de preferencias',
    'policies.prefCookiesContent': 'Recuerdan sus configuraciones como preferencias de idioma.',
    'policies.managingCookies': 'Gestión de cookies',
    'policies.managingCookiesContent': 'Puede gestionar preferencias de cookies en la configuración del navegador.',
    'policies.partnerDesc': 'Directrices para socios de restaurantes.',
    'policies.qualityStandards': 'Estándares de calidad',
    'policies.qualityStandardsContent': 'Los socios deben mantener estándares de seguridad alimentaria.',
    'policies.commission': 'Estructura de comisiones',
    'policies.commissionContent': 'La comisión estándar es 15-25% por pedido.',
    'policies.orderFulfillment': 'Cumplimiento de pedidos',
    'policies.orderFulfillmentContent': 'Los pedidos deben aceptarse en 5 minutos.',
    'policies.supportResources': 'Recursos de soporte',
    'policies.supportResourcesContent': 'Los socios tienen acceso al Portal de Socios y equipo de soporte.',
    'about.title1': 'Transformando Tu',
    'about.title2': 'Experiencia Gastronómica',
    'features.title': 'Pedidos de Comida por Voz',
    'features.qr': 'Pedido QR Instantáneo',
    'features.qrDesc': 'Escanea un código QR y haz tu pedido en segundos.',
    'features.multilang': 'Soporte Multilingüe',
    'features.multilangDesc': 'Soporte para 50+ idiomas.',
    'features.analytics': 'Análiticas Inteligentes',
    'features.analyticsDesc': 'Información en tiempo real sobre platos populares.',
    'how.subtitle': 'Proceso Simple',
    'how.title': 'Cómo Funciona',
    'how.step1Title': 'Escanea y Navega',
    'how.step1Desc': 'Escanea el código QR en tu mesa para acceder al menú.',
    'how.step2Title': 'Pide por Voz',
    'how.step2Desc': 'Habla en tu idioma. La IA entiende tu acento y preferencias.',
    'how.step3Title': 'Disfruta tu Comida',
    'how.step3Desc': 'Relájate mientras se prepara tu pedido con actualizaciones en tiempo real.',
    'testimonials.t1Name': 'Ahmad Karimi',
    'testimonials.t1Role': 'Amante de la comida, Tehrán',
    'testimonials.t1Text': '¡SaySavor cambió cómo pido comida. Hablo naturalmente y me entiende perfectamente!',
    'testimonials.t2Name': 'Samira Benali',
    'testimonials.t2Role': 'Dueña de restaurante, Casablanca',
    'testimonials.t2Text': 'Desde SaySavor nuestros pedidos aumentaron 40%. ¡Los análisis son increíbles!',
    'testimonials.t3Name': 'Ravi Mehta',
    'testimonials.t3Role': 'Foodie y viajero, Mumbai',
    'testimonials.t3Text': '¡Por fin una app que respeta mis restricciones dietarias. La IA lo entiende!',
    'cta.description': 'Únete a más de 500,000 amantes de la comida que usan SaySavor.',
    'cta.getStarted': 'Comenzar Gratis',
    'cta.scheduleDemo': 'Programar Demo',
    'persona.title': 'Elige Tu Camino',
    'persona.foodieDesc': 'Descubre cientos de restaurantes y pide en tu idioma.',
    'persona.foodieCta': 'Explorar como Foodie',
    'persona.partnerDesc': 'Aumenta tus ingresos con IA e inteligencia avanzada.',
    'persona.partnerCta': 'Unirse como Socio',
    'policies.subtitle': 'Nuestro Compromiso Contigo',
    'policies.transparencyPriority': 'La transparencia es nuestra prioridad',
    'policies.readMore': 'Leer más',
    'policies.privacyB1': 'Prácticas de recolección de datos',
    'policies.privacyB2': 'Compartir con terceros',
    'policies.privacyB3': 'Tus derechos',
    'policies.termsB1': 'Responsabilidades del usuario',
    'policies.termsB2': 'Limitaciones del servicio',
    'policies.termsB3': 'Políticas de cuenta',
    'policies.cookiesB1': 'Tipos de cookies',
    'policies.cookiesB2': 'Administrar preferencias',
    'policies.cookiesB3': 'Uso de analíticas',
    'policies.partnerB1': 'Estándares de calidad',
    'policies.partnerB2': 'Estructura de comisiones',
    'policies.partnerB3': 'Recursos de soporte',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À Propos',
    'nav.features': 'Fonctionnalités',
    'nav.howItWorks': 'Comment Ça Marche',
    'nav.foodie': 'Pour les Gourmets',
    'nav.partner': 'Pour les Partenaires',
    'nav.signIn': 'Se Connecter',
    'nav.getStarted': 'Commencer',
    'nav.policies': 'Politiques',
    'dash.overview': 'Aperçu',
    'dash.liveOrders': 'Commandes en direct',
    'dash.menuManager': 'Gestionnaire de menu',
    'dash.aiAssistant': 'Assistant IA',
    'dash.qrBuilder': 'Générateur de QR',
    'dash.settings': 'Paramètres',
    'dash.signOut': 'Déconnexion',
    'dash.adminPortal': 'Portail administrateur',
    'dash.morning': 'Bon Matin',
    'dash.afternoon': 'Bon Après-midi',
    'dash.evening': 'Bon Soir',
    'settings.title': 'Canevas Magique en Direct',
    'settings.subtitle': 'Concevez votre marque et configurez les opérations du système en temps réel.',
    'settings.saveChanges': 'Enregistrer les modifications',
    'settings.profile': 'Profil du restaurant',
    'settings.localization': 'Langue du portail',
    'settings.security': 'Sécurité et accès',
    'hero.badge': 'Technologie Vocale IA',
    'hero.headline1': 'Révolutionner le Goût',
    'hero.headline2': 'avec la Voix IA',
    'hero.subheadline': "Découvrez l'avenir de la découverte culinaire où votre voix déverrouille des voyages gastronomiques personnalisés.",
    'hero.tryVoice': 'Essayer la Recherche Vocale',
    'about.subtitle': 'À Propos de SaySavor',
    'about.title': 'Transformer Votre Expérience Culinaire',
    'about.description': "SaySavor combine une technologie vocale IA de pointe avec une passion pour la bonne cuisine.",
    'about.learnMore': 'En Savoir Plus',
    'about.globalReach': 'Portée Mondiale',
    'about.globalReachDesc': 'Découvrez des restaurants du monde entier.',
    'about.secure': 'Sécurisé et Privé',
    'about.secureDesc': 'Vos données sont protégées par une sécurité entreprise.',
    'about.fast': 'Ultra Rapide',
    'about.fastDesc': 'Obtenez des recommandations instantanées.',
    'features.badge': 'Fonctionnalités Puissantes',
    'features.title1': 'Conçu pour',
    'features.title2': 'Tous',
    'features.subtitle': 'Commande alimentaire qui vous comprend—votre culture, vos besoins.',
    'features.cultural': 'Contextualisation Culturelle',
    'features.culturalDesc': 'Filtrage intelligent basé sur les préférences alimentaires et les exigences religieuses.',
    'features.accessibility': 'Accessibilité Universelle',
    'features.accessibilityDesc': 'Conçu pour tous avec conformité WCAG 2.1.',
    'features.ai': 'IA Émotionnellement Intelligente',
    'features.aiDesc': 'Notre IA apprend vos préférences.',
    'howItWorks.title': 'Comment Ça Marche',
    'howItWorks.subtitle': 'Trois étapes simples pour votre repas parfait',
    'howItWorks.step1Title': 'Exprimez Votre Envie',
    'howItWorks.step1Desc': 'Dites-nous simplement ce que vous voulez. Notre IA comprend 50+ langues.',
    'howItWorks.step2Title': "L'IA Trouve Votre Match",
    'howItWorks.step2Desc': 'Notre moteur intelligent analyse vos préférences.',
    'howItWorks.step3Title': 'Savourez Votre Repas',
    'howItWorks.step3Desc': "Commandez d'un toucher et suivez votre repas.",
    'howItWorks.learnMore': 'En savoir plus sur notre processus',
    'testimonials.title': 'Ce Que Disent les Gens',
    'testimonials.subtitle': "Rejoignez des milliers d'utilisateurs satisfaits.",
    'cta.badge': 'Rejoignez 500K+ Utilisateurs',
    'cta.title': 'Prêt à Transformer Votre Expérience Culinaire?',
    'cta.subtitle': "Téléchargez SaySavor aujourd'hui.",
    'cta.downloadNow': 'Télécharger Maintenant',
    'cta.becomePartner': 'Devenir Partenaire',
    'persona.title1': 'Choisissez Votre',
    'persona.title2': 'Voyage',
    'persona.subtitle': 'Que vous soyez ici pour découvrir de la nourriture ou développer votre restaurant.',
    'persona.foodie': 'Je suis un Gourmet',
    'persona.foodieSubtitle': 'Découvrez des expériences culinaires conçues pour vous',
    'persona.partner': 'Je suis un Partenaire',
    'persona.partnerSubtitle': 'Développez votre restaurant avec des analyses intelligentes',
    'persona.getStarted': 'Commencer',
    'persona.exploreNow': 'Explorer',
    'persona.foodieFeature1': 'Commandes vocales dans votre langue',
    'persona.foodieFeature2': 'Recommandations de restaurants par IA',
    'persona.foodieFeature3': 'Filtrage des préférences culturelles et alimentaires',
    'persona.foodieFeature4': 'Suivi des commandes en temps réel',
    'persona.partnerFeature1': 'Tableau de bord analytique avancé',
    'persona.partnerFeature2': 'Prévision de la demande par IA',
    'persona.partnerFeature3': 'Gestion des commandes multicanal',
    'persona.partnerFeature4': 'Insights et tendances clients',
    'footer.description': 'Révolutionner les commandes alimentaires avec la technologie vocale IA.',
    'footer.product': 'Produit',
    'footer.company': 'Entreprise',
    'footer.resources': 'Ressources',
    'footer.legal': 'Légal',
    'footer.copyright': '© 2025 SaySavor. Tous droits réservés.',
    'footer.madeWith': 'Fait avec',
    'footer.forFoodLovers': 'pour les amoureux de la cuisine du monde entier',
    'policies.title': 'Juridique et Politiques',
    'policies.privacy': 'Politique de Confidentialité',
    'policies.terms': 'Conditions de Service',
    'policies.cookies': 'Politique des Cookies',
    'policies.partner': 'Directives Partenaires',
    'policies.heroDescription': 'La transparence est importante pour nous. Vous trouverez ici tous nos documents juridiques et politiques.',
    'policies.lastUpdated': 'Dernière mise à jour',
    'policies.december2025': 'Décembre 2025',
    'policies.contactTitle': 'Questions sur nos politiques?',
    'policies.contactDescription': 'Si vous avez des questions sur nos politiques, n\'hésitez pas à nous contacter.',
    'policies.contactButton': 'Contacter l\'équipe juridique',
    'policies.privacyDesc': 'Comment nous collectons, utilisons et protégeons vos données personnelles.',
    'policies.infoCollect': 'Informations que nous collectons',
    'policies.infoCollectContent': 'Nous collectons les informations que vous fournissez directement, comme les détails du compte et l\'historique.',
    'policies.howWeUse': 'Comment nous utilisons vos informations',
    'policies.howWeUseContent': 'Vos données sont utilisées pour traiter les commandes, personnaliser les recommandations et communiquer.',
    'policies.dataSharing': 'Partage des données',
    'policies.dataSharingContent': 'Nous partageons les informations nécessaires avec les partenaires restaurants pour exécuter les commandes.',
    'policies.yourRights': 'Vos droits',
    'policies.yourRightsContent': 'Vous avez le droit d\'accéder, de corriger ou de supprimer vos données.',
    'policies.termsDesc': 'Conditions d\'utilisation de SaySavor.',
    'policies.accountResp': 'Responsabilités du compte',
    'policies.accountRespContent': 'Vous êtes responsable de la sécurité de votre compte et de toutes les activités.',
    'policies.serviceUsage': 'Utilisation du service',
    'policies.serviceUsageContent': 'SaySavor est fourni pour les commandes alimentaires personnelles, non commerciales.',
    'policies.orderPolicies': 'Politiques de commande',
    'policies.orderPoliciesContent': 'Les commandes sont contraignantes une fois confirmées. Les politiques d\'annulation sont définies par les partenaires.',
    'policies.liability': 'Limitation de responsabilité',
    'policies.liabilityContent': 'SaySavor n\'est pas responsable des problèmes de qualité alimentaire.',
    'policies.cookiesDesc': 'Comment nous utilisons les cookies et les technologies de suivi.',
    'policies.essentialCookies': 'Cookies essentiels',
    'policies.essentialCookiesContent': 'Requis pour les fonctionnalités de base comme les sessions de connexion.',
    'policies.analyticsCookies': 'Cookies analytiques',
    'policies.analyticsCookiesContent': 'Nous aident à comprendre comment les utilisateurs interagissent avec la plateforme.',
    'policies.prefCookies': 'Cookies de préférences',
    'policies.prefCookiesContent': 'Se souviennent de vos paramètres comme les préférences linguistiques.',
    'policies.managingCookies': 'Gestion des cookies',
    'policies.managingCookiesContent': 'Vous pouvez gérer les préférences de cookies dans les paramètres du navigateur.',
    'policies.partnerDesc': 'Directives pour les partenaires restaurants.',
    'policies.qualityStandards': 'Normes de qualité',
    'policies.qualityStandardsContent': 'Les partenaires doivent maintenir les normes de sécurité alimentaire.',
    'policies.commission': 'Structure de commission',
    'policies.commissionContent': 'La commission standard est de 15-25% par commande.',
    'policies.orderFulfillment': 'Exécution des commandes',
    'policies.orderFulfillmentContent': 'Les commandes doivent être acceptées dans les 5 minutes.',
    'policies.supportResources': 'Ressources de support',
    'policies.supportResourcesContent': "Les partenaires ont accès au Portail Partenaires et à l'équipe de support.",
    'about.title1': 'Transformer Votre',
    'about.title2': 'Expérience Culinaire',
    'features.title': 'Commander par la Voix',
    'features.qr': 'Commande QR Instantanée',
    'features.qrDesc': 'Scannez un code QR et passez votre commande en secondes.',
    'features.multilang': 'Support Multilingue',
    'features.multilangDesc': 'Support pour 50+ langues.',
    'features.analytics': 'Analytiques Intelligentes',
    'features.analyticsDesc': 'Insights en temps réel sur les plats populaires.',
    'how.subtitle': 'Processus Simple',
    'how.title': 'Comment Ça Marche',
    'how.step1Title': 'Scannez et Parcourez',
    'how.step1Desc': 'Scannez le QR code sur votre table pour accéder au menu.',
    'how.step2Title': 'Commandez par la Voix',
    'how.step2Desc': "Parlez dans votre langue. L'IA comprend votre accent et préférences.",
    'how.step3Title': 'Dégustez Votre Repas',
    'how.step3Desc': 'Reposez-vous pendant que votre commande est préparée.',
    'testimonials.t1Name': 'Ahmad Karimi',
    'testimonials.t1Role': 'Amateur de nourriture, Téhéran',
    'testimonials.t1Text': "SaySavor a changé ma façon de commander. Je parle naturellement et il me comprend parfaitement!",
    'testimonials.t2Name': 'Samira Benali',
    'testimonials.t2Role': 'Propriétaire de restaurant, Casablanca',
    'testimonials.t2Text': 'Depuis SaySavor nos commandes ont augmenté de 40%. Excellentes analyses!',
    'testimonials.t3Name': 'Ravi Mehta',
    'testimonials.t3Role': 'Gourmet et voyageur, Mumbai',
    'testimonials.t3Text': 'Enfin une app qui respecte mes restrictions alimentaires!',
    'cta.description': 'Rejoignez plus de 500,000 amateurs de nourriture qui utilisent SaySavor.',
    'cta.getStarted': 'Commencer Gratuitement',
    'cta.scheduleDemo': 'Planifier une Démo',
    'persona.title': 'Choisissez Votre Voyage',
    'persona.foodieDesc': 'Découvrez des centaines de restaurants et commandez dans votre langue.',
    'persona.foodieCta': 'Explorer comme Gourmet',
    'persona.partnerDesc': "Augmentez vos revenus grâce à l'IA et aux analyses avancées.",
    'persona.partnerCta': 'Rejoindre comme Partenaire',
    'policies.subtitle': 'Notre Engagement Envers Vous',
    'policies.transparencyPriority': 'La transparence est notre priorité',
    'policies.readMore': 'Lire plus',
    'policies.privacyB1': 'Pratiques de collecte de données',
    'policies.privacyB2': 'Partage avec des tiers',
    'policies.privacyB3': 'Vos droits',
    'policies.termsB1': "Responsabilités de l'utilisateur",
    'policies.termsB2': 'Limitations du service',
    'policies.termsB3': 'Politiques de compte',
    'policies.cookiesB1': 'Types de cookies',
    'policies.cookiesB2': 'Gérer les préférences',
    'policies.cookiesB3': 'Utilisation des analyses',
    'policies.partnerB1': 'Normes de qualité',
    'policies.partnerB2': 'Structure de commission',
    'policies.partnerB3': 'Ressources de support',
  },
  zh: {
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.features': '功能特点',
    'nav.howItWorks': '工作原理',
    'nav.foodie': '美食家',
    'nav.partner': '合作伙伴',
    'nav.signIn': '登录',
    'nav.getStarted': '开始使用',
    'nav.policies': '政策',
    'dash.overview': '概览',
    'dash.liveOrders': '实时订单',
    'dash.menuManager': '菜单管理',
    'dash.aiAssistant': 'AI 助手',
    'dash.qrBuilder': 'QR 生成器',
    'dash.settings': '设置',
    'dash.signOut': '登出',
    'dash.adminPortal': '管理门户',
    'dash.morning': '早上好',
    'dash.afternoon': '下午好',
    'dash.evening': '晚上好',
    'settings.title': '实时魔法画布',
    'settings.subtitle': '实时设计您的品牌并配置系统操作。',
    'settings.saveChanges': '保存更改',
    'settings.profile': '餐厅简介',
    'settings.localization': '门户语言',
    'settings.security': '安全与访问',
    'hero.badge': 'AI驱动语音技术',
    'hero.headline1': '革新味觉',
    'hero.headline2': '通过语音AI',
    'hero.subheadline': '体验美食发现的未来，您的声音将开启个性化的美食之旅。',
    'hero.tryVoice': '尝试语音搜索',
    'about.subtitle': '关于SaySavor',
    'about.title': '改变您的美食体验',
    'about.description': 'SaySavor将尖端语音AI技术与对美食的热情相结合。',
    'about.learnMore': '了解更多',
    'about.globalReach': '全球覆盖',
    'about.globalReachDesc': '发现世界各地的餐厅。',
    'about.secure': '安全私密',
    'about.secureDesc': '您的数据受到企业级安全保护。',
    'about.fast': '闪电般快速',
    'about.fastDesc': '获得即时推荐。',
    'features.badge': '强大功能',
    'features.title1': '为',
    'features.title2': '所有人设计',
    'features.subtitle': '了解您的美食订购—您的文化、您的需求。',
    'features.cultural': '文化语境化',
    'features.culturalDesc': '基于饮食偏好和宗教要求的智能过滤。',
    'features.accessibility': '通用无障碍',
    'features.accessibilityDesc': '符合WCAG 2.1标准，为所有人设计。',
    'features.ai': '情感智能AI',
    'features.aiDesc': '我们的AI学习您的偏好。',
    'howItWorks.title': '工作原理',
    'howItWorks.subtitle': '三个简单步骤享用完美餐点',
    'howItWorks.step1Title': '说出您的渴望',
    'howItWorks.step1Desc': '只需告诉我们您想要什么。我们的AI理解50+种语言。',
    'howItWorks.step2Title': 'AI找到您的匹配',
    'howItWorks.step2Desc': '我们的智能引擎分析您的偏好。',
    'howItWorks.step3Title': '享受您的美食',
    'howItWorks.step3Desc': '一键下单，实时追踪您的美食。',
    'howItWorks.learnMore': '了解更多关于我们的流程',
    'testimonials.title': '用户评价',
    'testimonials.subtitle': '加入成千上万满意的用户。',
    'cta.badge': '加入500K+用户',
    'cta.title': '准备好改变您的美食体验了吗？',
    'cta.subtitle': '今天就下载SaySavor。',
    'cta.downloadNow': '立即下载',
    'cta.becomePartner': '成为合作伙伴',
    'persona.title1': '选择您的',
    'persona.title2': '旅程',
    'persona.subtitle': '无论您是来发现美食还是发展餐厅业务。',
    'persona.foodie': '我是美食家',
    'persona.foodieSubtitle': '发现专为您设计的美食体验',
    'persona.partner': '我是合作伙伴',
    'persona.partnerSubtitle': '用智能分析发展您的餐厅',
    'persona.getStarted': '开始使用',
    'persona.exploreNow': '立即探索',
    'persona.foodieFeature1': '用您的语言语音点餐',
    'persona.foodieFeature2': 'AI精选餐厅推荐',
    'persona.foodieFeature3': '文化和饮食偏好过滤',
    'persona.foodieFeature4': '实时订单追踪',
    'persona.partnerFeature1': '高级分析仪表板',
    'persona.partnerFeature2': 'AI驱动需求预测',
    'persona.partnerFeature3': '多渠道订单管理',
    'persona.partnerFeature4': '客户洞察和趋势',
    'footer.description': '用语音AI技术革新美食订购。',
    'footer.product': '产品',
    'footer.company': '公司',
    'footer.resources': '资源',
    'footer.legal': '法律',
    'footer.copyright': '© 2025 SaySavor。保留所有权利。',
    'footer.madeWith': '用心制作',
    'footer.forFoodLovers': '献给全球美食爱好者',
    'policies.title': '法律与政策',
    'policies.privacy': '隐私政策',
    'policies.terms': '服务条款',
    'policies.cookies': 'Cookie政策',
    'policies.partner': '合作伙伴指南',
    'policies.heroDescription': '透明度对我们很重要。您可以在这里找到我们所有的法律文件和政策。',
    'policies.lastUpdated': '最后更新',
    'policies.december2025': '2025年12月',
    'policies.contactTitle': '对我们的政策有疑问？',
    'policies.contactDescription': '如果您对我们的政策有任何疑问，请随时与我们联系。',
    'policies.contactButton': '联系法务团队',
    'policies.privacyDesc': '我们如何收集、使用和保护您的个人数据。',
    'policies.infoCollect': '我们收集的信息',
    'policies.infoCollectContent': '我们收集您直接提供的信息，如账户详情、订单历史。',
    'policies.howWeUse': '我们如何使用您的信息',
    'policies.howWeUseContent': '您的数据用于处理订单、个性化推荐和与您沟通。',
    'policies.dataSharing': '数据共享',
    'policies.dataSharingContent': '我们与餐厅合作伙伴共享必要信息以完成订单。',
    'policies.yourRights': '您的权利',
    'policies.yourRightsContent': '您有权访问、更正或删除您的数据。',
    'policies.termsDesc': '使用SaySavor的条款和条件。',
    'policies.accountResp': '账户责任',
    'policies.accountRespContent': '您负责维护账户安全和账户下的所有活动。',
    'policies.serviceUsage': '服务使用',
    'policies.serviceUsageContent': 'SaySavor提供个人非商业性食品订购服务。',
    'policies.orderPolicies': '订单政策',
    'policies.orderPoliciesContent': '订单一旦确认即具有约束力。取消政策由餐厅合作伙伴制定。',
    'policies.liability': '责任限制',
    'policies.liabilityContent': 'SaySavor不对食品质量问题负责。',
    'policies.cookiesDesc': '我们如何使用Cookie和跟踪技术。',
    'policies.essentialCookies': '必要Cookie',
    'policies.essentialCookiesContent': '登录会话和购物车管理等基本功能所必需。',
    'policies.analyticsCookies': '分析Cookie',
    'policies.analyticsCookiesContent': '帮助我们了解用户如何与平台互动。',
    'policies.prefCookies': '偏好Cookie',
    'policies.prefCookiesContent': '记住您的设置，如语言偏好。',
    'policies.managingCookies': '管理Cookie',
    'policies.managingCookiesContent': '您可以在浏览器设置中管理Cookie偏好。',
    'policies.partnerDesc': '餐厅合作伙伴指南。',
    'policies.qualityStandards': '质量标准',
    'policies.qualityStandardsContent': '合作伙伴必须保持食品安全标准。',
    'policies.commission': '佣金结构',
    'policies.commissionContent': '标准佣金为每单15-25%。',
    'policies.orderFulfillment': '订单履行',
    'policies.orderFulfillmentContent': '订单必须在5分钟内接受。',
    'policies.supportResources': '支持资源',
    'policies.supportResourcesContent': '合作伙伴可以访问合作伙伴门户和专属支持团队。',
  },
  tr: {
    'nav.home': 'Ana Sayfa',
    'nav.about': 'Hakkımızda',
    'nav.features': 'Özellikler',
    'nav.howItWorks': 'Nasıl Çalışır',
    'nav.foodie': 'Gurmelere',
    'nav.partner': 'İş Ortaklarına',
    'nav.signIn': 'Giriş Yap',
    'nav.getStarted': 'Başla',
    'nav.policies': 'Politikalar',
    'dash.overview': 'Genel Bakış',
    'dash.liveOrders': 'Canlı Siparişler',
    'dash.menuManager': 'Menü Yöneticisi',
    'dash.aiAssistant': 'AI Asistanı',
    'dash.qrBuilder': 'QR Oluşturucu',
    'dash.settings': 'Ayarlar',
    'dash.signOut': 'Çıkış Yap',
    'dash.adminPortal': 'Yönetici Portalı',
    'dash.morning': 'Günaydın',
    'dash.afternoon': 'Tünaydın',
    'dash.evening': 'İyi Akşamlar',
    'settings.title': 'Canlı Sihirli Tuval',
    'settings.subtitle': 'Markanızı tasarlayın ve sistem operasyonlarını gerçek zamanlı olarak yapılandırın.',
    'settings.saveChanges': 'Değişiklikleri Kaydet',
    'settings.profile': 'Restoran Profili',
    'settings.localization': 'Portal Dili',
    'settings.security': 'Güvenlik ve Erişim',
    'hero.badge': 'AI Destekli Ses Teknolojisi',
    'hero.headline1': 'Tadı Devrimleştiriyoruz',
    'hero.headline2': 'Sesli AI ile',
    'hero.subheadline': 'Sesinizin kişiselleştirilmiş mutfak yolculuklarının kilidini açtığı yemek keşfinin geleceğini deneyimleyin.',
    'hero.tryVoice': 'Sesli Aramayı Dene',
    'about.subtitle': 'SaySavor Hakkında',
    'about.title': 'Yemek Deneyiminizi Dönüştürüyoruz',
    'about.description': 'SaySavor, son teknoloji sesli AI teknolojisini harika yemek tutkusuyla birleştiriyor.',
    'about.learnMore': 'Daha Fazla Bilgi',
    'about.globalReach': 'Küresel Erişim',
    'about.globalReachDesc': 'Dünyanın her yerinden restoranları keşfedin.',
    'about.secure': 'Güvenli ve Özel',
    'about.secureDesc': 'Verileriniz kurumsal güvenlikle korunur.',
    'about.fast': 'Işık Hızında',
    'about.fastDesc': 'Anında öneriler alın.',
    'features.badge': 'Güçlü Özellikler',
    'features.title1': 'Herkes İçin',
    'features.title2': 'Tasarlandı',
    'features.subtitle': 'Sizi anlayan yemek siparişi—kültürünüz, ihtiyaçlarınız.',
    'features.cultural': 'Kültürel Bağlam',
    'features.culturalDesc': 'Diyet tercihleri ve dini gereksinimlere göre akıllı filtreleme.',
    'features.accessibility': 'Evrensel Erişilebilirlik',
    'features.accessibilityDesc': 'WCAG 2.1 uyumluluğu ile herkes için tasarlandı.',
    'features.ai': 'Duygusal Zeka AI',
    'features.aiDesc': 'AI tercihlerinizi öğrenir.',
    'howItWorks.title': 'Nasıl Çalışır',
    'howItWorks.subtitle': 'Mükemmel yemeğiniz için üç basit adım',
    'howItWorks.step1Title': 'İsteğinizi Söyleyin',
    'howItWorks.step1Desc': 'Sadece ne istediğinizi söyleyin. AI 50+ dil anlar.',
    'howItWorks.step2Title': 'AI Eşleşmenizi Bulur',
    'howItWorks.step2Desc': 'Akıllı motorumuz tercihlerinizi analiz eder.',
    'howItWorks.step3Title': 'Yemeğinizin Keyfini Çıkarın',
    'howItWorks.step3Desc': 'Tek dokunuşla sipariş verin ve yemeğinizi takip edin.',
    'howItWorks.learnMore': 'Sürecimiz hakkında daha fazla bilgi edinin',
    'testimonials.title': 'İnsanlar Ne Diyor',
    'testimonials.subtitle': 'Binlerce memnun kullanıcıya katılın.',
    'cta.badge': '500K+ Kullanıcıya Katılın',
    'cta.title': 'Yemek Deneyiminizi Dönüştürmeye Hazır mısınız?',
    'cta.subtitle': "Bugün SaySavor'u indirin.",
    'cta.downloadNow': 'Şimdi İndir',
    'cta.becomePartner': 'Ortak Olun',
    'persona.title1': 'Yolculuğunuzu',
    'persona.title2': 'Seçin',
    'persona.subtitle': 'İster yemek keşfetmeye ister restoranınızı büyütmeye gelin.',
    'persona.foodie': 'Ben Bir Gurmeyim',
    'persona.foodieSubtitle': 'Sizin için tasarlanmış mutfak deneyimlerini keşfedin',
    'persona.partner': 'Ben Bir Ortağım',
    'persona.partnerSubtitle': 'Akıllı analizlerle restoranınızı büyütün',
    'persona.getStarted': 'Başla',
    'persona.exploreNow': 'Keşfet',
    'persona.foodieFeature1': 'Kendi dilinizde sesli sipariş',
    'persona.foodieFeature2': 'AI küratörlüğünde restoran önerileri',
    'persona.foodieFeature3': 'Kültürel ve diyet tercihi filtreleme',
    'persona.foodieFeature4': 'Gerçek zamanlı sipariş takibi',
    'persona.partnerFeature1': 'Gelişmiş analitik panosu',
    'persona.partnerFeature2': 'AI destekli talep tahmini',
    'persona.partnerFeature3': 'Çok kanallı sipariş yönetimi',
    'persona.partnerFeature4': 'Müşteri içgörüleri ve trendler',
    'footer.description': 'Sesli AI teknolojisiyle yemek siparişinde devrim.',
    'footer.product': 'Ürün',
    'footer.company': 'Şirket',
    'footer.resources': 'Kaynaklar',
    'footer.legal': 'Yasal',
    'footer.copyright': '© 2025 SaySavor. Tüm hakları saklıdır.',
    'footer.madeWith': 'Yapıldı',
    'footer.forFoodLovers': 'dünya genelindeki yemek severler için',
    'policies.title': 'Yasal ve Politikalar',
    'policies.privacy': 'Gizlilik Politikası',
    'policies.terms': 'Hizmet Şartları',
    'policies.cookies': 'Çerez Politikası',
    'policies.partner': 'Partner Kılavuzu',
    'policies.heroDescription': 'Şeffaflık bizim için önemlidir. Tüm yasal belgelerimizi ve politikalarımızı burada bulabilirsiniz.',
    'policies.lastUpdated': 'Son güncelleme',
    'policies.december2025': 'Aralık 2025',
    'policies.contactTitle': 'Politikalarımız hakkında sorularınız mı var?',
    'policies.contactDescription': 'Politikalarımız hakkında sorularınız varsa, lütfen bizimle iletişime geçin.',
    'policies.contactButton': 'Hukuk ekibiyle iletişime geçin',
    'policies.privacyDesc': 'Kişisel verilerinizi nasıl topluyor, kullanıyor ve koruyoruz.',
    'policies.infoCollect': 'Topladığımız bilgiler',
    'policies.infoCollectContent': 'Hesap detayları, sipariş geçmişi gibi doğrudan sağladığınız bilgileri topluyoruz.',
    'policies.howWeUse': 'Bilgilerinizi nasıl kullanıyoruz',
    'policies.howWeUseContent': 'Verileriniz siparişleri işlemek, önerileri kişiselleştirmek ve sizinle iletişim kurmak için kullanılır.',
    'policies.dataSharing': 'Veri paylaşımı',
    'policies.dataSharingContent': 'Siparişleri tamamlamak için restoran ortaklarıyla gerekli bilgileri paylaşıyoruz.',
    'policies.yourRights': 'Haklarınız',
    'policies.yourRightsContent': 'Verilerinize erişme, düzeltme veya silme hakkınız vardır.',
    'policies.termsDesc': 'SaySavor kullanım şartları ve koşulları.',
    'policies.accountResp': 'Hesap sorumlulukları',
    'policies.accountRespContent': 'Hesabınızın güvenliğinden ve altındaki tüm etkinliklerden siz sorumlusunuz.',
    'policies.serviceUsage': 'Hizmet kullanımı',
    'policies.serviceUsageContent': 'SaySavor kişisel, ticari olmayan yemek siparişi için sağlanmaktadır.',
    'policies.orderPolicies': 'Sipariş politikaları',
    'policies.orderPoliciesContent': 'Siparişler onaylandıktan sonra bağlayıcıdır. İptal politikaları ortaklar tarafından belirlenir.',
    'policies.liability': 'Sorumluluk sınırı',
    'policies.liabilityContent': 'SaySavor yemek kalitesi sorunlarından sorumlu değildir.',
    'policies.cookiesDesc': 'Çerezleri ve izleme teknolojilerini nasıl kullanıyoruz.',
    'policies.essentialCookies': 'Zorunlu çerezler',
    'policies.essentialCookiesContent': 'Oturum açma ve sepet yönetimi gibi temel işlevler için gereklidir.',
    'policies.analyticsCookies': 'Analitik çerezler',
    'policies.analyticsCookiesContent': 'Kullanıcıların platformla nasıl etkileşimde bulunduğunu anlamamıza yardımcı olur.',
    'policies.prefCookies': 'Tercih çerezleri',
    'policies.prefCookiesContent': 'Dil tercihleri gibi ayarlarınızı hatırlar.',
    'policies.managingCookies': 'Çerez yönetimi',
    'policies.managingCookiesContent': 'Tarayıcı ayarlarında çerez tercihlerini yönetebilirsiniz.',
    'policies.partnerDesc': 'Restoran ortakları için kılavuz.',
    'policies.qualityStandards': 'Kalite standartları',
    'policies.qualityStandardsContent': 'Ortaklar gıda güvenliği standartlarını korumalıdır.',
    'policies.commission': 'Komisyon yapısı',
    'policies.commissionContent': 'Standart komisyon sipariş başına %15-25\'tir.',
    'policies.orderFulfillment': 'Sipariş karşılama',
    'policies.orderFulfillmentContent': 'Siparişler 5 dakika içinde kabul edilmelidir.',
    'policies.supportResources': 'Destek kaynakları',
    'policies.supportResourcesContent': 'Ortaklar Partner Portalı ve özel destek ekibine erişebilir.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const isRTL = language === 'ur' || language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-urdu' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
